/*
 * File: charset_ui.h
 * Contains: Declarations of module objects, user create procedures,
 *           and callbacks.
 *
 * This file was generated by dtcodegen, from module charset
 *
 *    ** DO NOT MODIFY BY HAND - ALL MODIFICATIONS WILL BE LOST **
 */
#ifndef _CHARSET_UI_H_
#define _CHARSET_UI_H_

#include <stdlib.h>
#include <X11/Intrinsic.h>
#include "dtb_utils.h"

/*
 * User Interface Objects
 */
/*
 * Shared data structures
 */

typedef struct {
    Widget	A_item;
    Widget	B_item;
    Widget	C_item;
    Widget	D_item;
    Widget	E_item;
    Widget	F_item;
    Widget	G_item;
    Widget	H_item;
    Widget	I_item;
    Widget	J_item;
    Widget	K_item;
    Widget	L_item;
    Widget	M_item;
    Widget	N_item;
    Widget	O_item;
    Widget	P_item;
    Widget	Q_item;
    Widget	R_item;
    Widget	S_item;
    Widget	T_item;
    Widget	U_item;
    Widget	V_item;
    Widget	W_item;
    Widget	X_item;
    Widget	Y_item;
    Widget	Z_item;
    Widget	one_item;
    Widget	two_item;
    Widget	three_item;
    Widget	four_item;
    Widget	five_item;
    Widget	six_item;
    Widget	seven_item;
    Widget	eight_item;
    Widget	nine_item;
    Widget	zero_item;
    Widget	dot_item;
    Widget	comma_item;
    Widget	exclamation_item;
    Widget	question_item;
    Widget	equal_item;
    Widget	dash_item;
    Widget	underline_item;
    Widget	colon_item;
    Widget	semicolon_item;
    Widget	apostrophe_item;
    Widget	quotation_item;
    Widget	slash_item;
    Widget	open_bracket_item;
    Widget	close_bracket_item;
    Widget	dollar_item;
    Widget	ampersand_item;
    Widget	at_item;
    Widget	begin_item;
    Widget	end_item;
} CharsetCharBoxItemsRec, *CharsetCharBoxItems;
typedef struct {
    Widget	lesson1_item;
    Widget	lesson2_item;
    Widget	lesson3_item;
    Widget	lesson4_item;
    Widget	lesson5_item;
    Widget	lesson6_item;
    Widget	lesson7_item;
    Widget	lesson8_item;
    Widget	lesson9_item;
    Widget	lesson10_item;
    Widget	lesson11_item;
    Widget	lesson12_item;
    Widget	lesson13_item;
    Widget	lesson14_item;
    Widget	lesson15_item;
    Widget	lesson16_item;
    Widget	lesson17_item;
    Widget	lesson18_item;
    Widget	lesson19_item;
    Widget	lesson20_item;
    Widget	lesson21_item;
    Widget	lesson22_item;
    Widget	lesson23_item;
    Widget	lesson24_item;
    Widget	lesson25_item;
    Widget	user_item;
} CharsetLessonBoxItemsRec, *CharsetLessonBoxItems;
typedef struct {
    Widget	only_new;
    Widget	one;
    Widget	all;
} CharsetStageBoxItemsRec, *CharsetStageBoxItems;
typedef struct {
    Widget	A_item;
    Widget	B_item;
    Widget	C_item;
    Widget	D_item;
    Widget	E_item;
    Widget	F_item;
    Widget	G_item;
    Widget	H_item;
    Widget	I_item;
    Widget	J_item;
    Widget	K_item;
    Widget	L_item;
    Widget	M_item;
    Widget	N_item;
    Widget	O_item;
    Widget	P_item;
    Widget	Q_item;
    Widget	R_item;
    Widget	S_item;
    Widget	T_item;
    Widget	U_item;
    Widget	V_item;
    Widget	W_item;
    Widget	X_item;
    Widget	Y_item;
    Widget	Z_item;
    Widget	one_item;
    Widget	two_item;
    Widget	three_item;
    Widget	four_item;
    Widget	five_item;
    Widget	six_item;
    Widget	seven_item;
    Widget	eight_item;
    Widget	nine_item;
    Widget	zero_item;
    Widget	dot_item;
    Widget	comma_item;
    Widget	exclamation_item;
    Widget	question_item;
    Widget	equal_item;
    Widget	dash_item;
    Widget	underline_item;
    Widget	colon_item;
    Widget	semicolon_item;
    Widget	apostrophe_item;
    Widget	quotation_item;
    Widget	slash_item;
    Widget	open_bracket_item;
    Widget	close_bracket_item;
    Widget	dollar_item;
    Widget	ampersand_item;
    Widget	at_item;
    Widget	begin_item;
    Widget	end_item;
} CharsetCharBoxChoiceItemsRec, *CharsetCharBoxChoiceItems;
typedef struct {
    Widget	lesson1_item;
    Widget	lesson2_item;
    Widget	lesson3_item;
    Widget	lesson4_item;
    Widget	lesson5_item;
    Widget	lesson6_item;
    Widget	lesson7_item;
    Widget	lesson8_item;
    Widget	lesson9_item;
    Widget	lesson10_item;
    Widget	lesson11_item;
    Widget	lesson12_item;
    Widget	lesson13_item;
    Widget	lesson14_item;
    Widget	lesson15_item;
    Widget	lesson16_item;
    Widget	lesson17_item;
    Widget	lesson18_item;
    Widget	lesson19_item;
    Widget	lesson20_item;
    Widget	lesson21_item;
    Widget	lesson22_item;
    Widget	lesson23_item;
    Widget	lesson24_item;
    Widget	lesson25_item;
    Widget	user_item;
} CharsetLessonBoxMenuItemsRec, *CharsetLessonBoxMenuItems;
typedef struct {
    Widget	only_new;
    Widget	one;
    Widget	all;
} CharsetStageBoxMenuItemsRec, *CharsetStageBoxMenuItems;
typedef struct
{
    Boolean	initialized;
    
    Widget	charsetDialog;	/* object "charsetDialog" */
    Widget	charsetDialog_shellform;
    Widget	charsetDialog_panedwin;
    Widget	charsetDialog_form;
    
    Widget	dialog_button_panel;
    Widget	controlpane;
    
    Widget	charBox_rowcolumn;	/* object "charBox" */
    Widget	charBox_label;
    Widget	charBox;
    CharsetCharBoxItemsRec	charBox_items;
    
    Widget	lessonBox_rowcolumn;	/* object "lessonBox" */
    Widget	lessonBox_menu;
    Widget	lessonBox_label;
    Widget	lessonBox;
    CharsetLessonBoxItemsRec	lessonBox_items;
    
    Widget	separator;
    
    Widget	stageBox_rowcolumn;	/* object "stageBox" */
    Widget	stageBox_menu;
    Widget	stageBox_label;
    Widget	stageBox;
    CharsetStageBoxItemsRec	stageBox_items;
    
    Widget	separator2;
    Widget	charset_ok;
    Widget	charset_reset;
    Widget	charset_cancel;
} DtbCharsetCharsetDialogInfoRec, *DtbCharsetCharsetDialogInfo;



extern DtbCharsetCharsetDialogInfoRec dtb_charset_charset_dialog;
extern DtbMessageDataRec dtb_charset_dont_deselect;

/*
 * Structure Clear Procedures: These set the fields to NULL
 */
int dtbCharsetCharsetDialogInfo_clear(DtbCharsetCharsetDialogInfo instance);

/*
 * Structure Initialization Procedures: These create the widgets
 */
int dtb_charset_charset_dialog_initialize(
    DtbCharsetCharsetDialogInfo	instance,
    Widget	parent
);
int dtb_charset_dont_deselect_initialize(DtbMessageData instance);

/*
 * User Callbacks
 */
void setCharset(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void resetCharset(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void setLesson(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void setLessonStage(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void initCharsetDialog(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void dontDeselect(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void setToUserLesson(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);

/*
 * Connections
 */
void charset_charset_ok_CB1(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void charset_charset_cancel_CB1(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
#endif /* _CHARSET_UI_H_ */
