/*** DTB_USER_CODE_START vvv Add file header below vvv ***/
/*** DTB_USER_CODE_END   ^^^ Add file header above ^^^ ***/

/*
 * File: connect_stubs.c
 * Contains: Module callbacks and connection functions
 *
 * This file was generated by dtcodegen, from module connect
 *
 * Any text may be added between the DTB_USER_CODE_START and
 * DTB_USER_CODE_END comments (even non-C code). Descriptive comments
 * are provided only as an aid.
 *
 *  ** EDIT ONLY WITHIN SECTIONS MARKED WITH DTB_USER_CODE COMMENTS.  **
 *  ** ALL OTHER MODIFICATIONS WILL BE OVERWRITTEN. DO NOT MODIFY OR  **
 *  ** DELETE THE GENERATED COMMENTS!                                 **
 */

#include <stdio.h>
#include <Xm/Xm.h>
#include "dtb_utils.h"
#include "connect_ui.h"

/*
 * Header files for cross-module connections
 */
#include "main_ui.h"


/**************************************************************************
 *** DTB_USER_CODE_START
 ***
 *** All necessary header files have been included.
 ***
 *** Add include files, types, macros, externs, and user functions here.
 ***/
#include <Xm/PushB.h>

#include "network.h"

static Widget networkBoxItems[256];
static int nNetworkBoxItems = 0;

int connect_ScanNetworks();
/*** DTB_USER_CODE_END
 ***
 *** End of user code section
 ***
 **************************************************************************/



void 
connect_connect_cancel_CB1(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    DtbConnectConnectInfo	dtbTarget = (DtbConnectConnectInfo)clientData;
    DtbConnectConnectInfo	instance = dtbTarget;	/* obsolete */
    
    if (!(dtbTarget->initialized))
    {
        dtb_connect_connect_initialize(dtbTarget, dtb_main_mainwindow.mainwindow);
    }
    XtUnmanageChild(instance->connect_shellform);
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
connectOk(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
doRescan(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
	connect_ScanNetworks();
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}



/**************************************************************************
 *** DTB_USER_CODE_START
 ***
 *** All automatically-generated data and functions have been defined.
 ***
 *** Add new functions here, or at the top of the file.
 ***/
int connect_ScanNetworks()
{
	XmString netnumString;
	int nNetworks;
	Cardinal n;
	Arg args[1];
	int networks[256];
	uint32_t defaultNet = 0;

	Widget wNetworks[256];
	WidgetList children;

	for (n = 0; n < nNetworkBoxItems; n++) {
		XtDestroyWidget(networkBoxItems[n]);
	}

	nNetworks = getAvailableNetworks(networks, 256, &defaultNet);
	if (nNetworks < 0)
		return nNetworks;

	for (n = 0; n < nNetworks; n++) {
		char str[9];
		sprintf(str, "%x", networks[n]);
		netnumString = XmStringCreateLocalized(str);
		networkBoxItems[n] = XtVaCreateWidget(str,
			xmPushButtonWidgetClass,
			dtb_connect_connect.networkBox_menu,
			XmNlabelString, netnumString,
			NULL);
		XmStringFree(netnumString);
	}
	nNetworkBoxItems = nNetworks;
	XtVaGetValues(dtb_connect_connect.networkBox_menu,
			XmNchildren, &children, XmNnumChildren, &n, NULL);
	XtManageChildren(children, n);

	n = 0;
	if (defaultNet >= 0) {
		XtVaSetValues(dtb_connect_connect.networkBox, XmNmenuHistory, networkBoxItems[defaultNet], NULL);
	}
	return nNetworks;
}
/*** DTB_USER_CODE_END
 ***
 *** End of user code section
 ***
 **************************************************************************/


