/* XPM */
static char * connect_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 3 1 -1 -1",
/* colors */
" 	s none	m none	c none",
".	s iconColor1	m black	c black",
"X	s iconColor6	m white	c yellow",
/* pixels */
"                                ",
"                       .        ",
"                      .         ",
"                     ..         ",
"                    ..          ",
"                   ..           ",
"                  .X.           ",
"                 .X.            ",
"                .X.             ",
"               .XX.             ",
"             ..XX.              ",
"            .XXX.               ",
"           .XXXX.               ",
"          .XXXX.............    ",
"         .XXXXXXXXXXXXXXXX.     ",
"        .XXXXXXXXXXXXXXX..      ",
"       .XXXXXXX...XXXXX.        ",
"      .XXXX.... .XXXXX.         ",
"     .X....    .XXXXX.          ",
"    ...        .XXX..           ",
"              .XXX.             ",
"             .XXX.              ",
"            .XXX.               ",
"            .XX.                ",
"           .X..                 ",
"          .X.                   ",
"         .X.                    ",
"        .X.                     ",
"        ..                      ",
"       .                        ",
"      .                         ",
"                                "};
