/*
 * File: connect_ui.c
 * Contains: user module object initialize and create functions
 *
 * This file was generated by dtcodegen, from module connect
 *
 *    ** DO NOT MODIFY BY HAND - ALL MODIFICATIONS WILL BE LOST **
 */


#include <stdlib.h>
#include <X11/Intrinsic.h>
#include <Xm/DialogS.h>
#include <Xm/Form.h>
#include <Xm/PanedW.h>
#include <Xm/RowColumn.h>
#include <Xm/Separator.h>
#include <Xm/Label.h>
#include <Xm/TextF.h>
#include <Xm/PushB.h>
#include "dtb_utils.h"
#include "morsetutor.h"
#include "connect_ui.h"


DtbConnectConnectInfoRec	dtb_connect_connect = 
{
    False	 /* initialized */
};
DtbMessageDataRec	dtb_connect_netunreach;
DtbMessageDataRec	dtb_connect_noderesponse;

/*
 * Widget create procedure decls
 */
static int dtb_connect_connect_create(
    DtbConnectConnectInfo	instance,
    Widget	parent
);
static int dtb_connect_dialog_button_panel_create(
    DtbConnectConnectInfo	instance,
    Widget	parent
);
static int dtb_connect_controlpane_create(
    DtbConnectConnectInfo	instance,
    Widget	parent
);
static int dtb_connect_network_box_create(
    DtbConnectConnectInfo	instance,
    Widget	parent
);
static int dtb_connect_node_box_create(
    DtbConnectConnectInfo	instance,
    Widget	parent
);
static int dtb_connect_separator_create(
    DtbConnectConnectInfo	instance,
    Widget	parent
);
static int dtb_connect_connect_ok_create(
    DtbConnectConnectInfo	instance,
    Widget	parent
);
static int dtb_connect_connect_rescan_create(
    DtbConnectConnectInfo	instance,
    Widget	parent
);
static int dtb_connect_connect_cancel_create(
    DtbConnectConnectInfo	instance,
    Widget	parent
);

int 
dtbConnectConnectInfo_clear(DtbConnectConnectInfo instance)
{
    memset((void *)(instance), 0, sizeof(*instance));
    return 0;
}

int 
dtb_connect_connect_initialize(
    DtbConnectConnectInfo instance,
    Widget parent
)
{
    WidgetList	children = NULL;
    int		numChildren = 0;
    if (instance->initialized)
    {
        return 0;
    }
    instance->initialized = True;

    dtb_connect_connect_create(instance,
        parent);
    dtb_connect_dialog_button_panel_create(instance,
        instance->connect_panedwin);
    dtb_connect_controlpane_create(instance,
        instance->connect_form);
    dtb_connect_network_box_create(instance,
        instance->controlpane);
    dtb_connect_node_box_create(instance,
        instance->controlpane);
    dtb_connect_separator_create(instance,
        instance->controlpane);
    dtb_connect_connect_ok_create(instance,
        instance->dialog_button_panel);
    dtb_connect_connect_rescan_create(instance,
        instance->dialog_button_panel);
    dtb_connect_connect_cancel_create(instance,
        instance->dialog_button_panel);
    
    /*
     * Add widget-reference resources.
     */
    
    XtVaSetValues(instance->connect_shellform,
        XmNdefaultButton, instance->connect_ok,
        NULL);
    
    XtVaSetValues(instance->nodeBox_rowcolumn,
        XmNtopWidget, instance->networkBox_rowcolumn,
        NULL);
    
    XtVaSetValues(instance->separator,
        XmNtopWidget, instance->nodeBox_rowcolumn,
        NULL);
    
    /*
     * Call utility functions to do group layout
     */
    
    /*
     * Make Dialog Button-Panel & Footer a fixed height
     */
    {
        Dimension	pane_height;

        XtVaGetValues(instance->dialog_button_panel,
            XmNheight, &pane_height,
            NULL);
        XtVaSetValues(instance->dialog_button_panel,
            XmNpaneMinimum,   pane_height,
            XmNpaneMaximum,   pane_height,
            NULL);

    }
    
    /*
     * Manage the tree, from the bottom up.
     */
    XtVaGetValues(instance->networkBox_rowcolumn,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->nodeBox_rowcolumn,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->controlpane,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->connect_form,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->dialog_button_panel,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtManageChild(instance->connect_form);
    XtManageChild(instance->dialog_button_panel);
    XtVaGetValues(instance->connect_shellform,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    /*
     * Turn off traversal for invisible sash in dialog's PanedWindow
     */
    dtb_remove_sash_focus(instance->connect_panedwin);
    
    /*
     * Add User and Connection callbacks
     */
    	XtAddCallback(instance->connect,
		XmNpopupCallback, doRescan,
    		(XtPointer)&(*instance));
	XtAddCallback(instance->connect_ok,
		XmNactivateCallback, connectOk,
		(XtPointer)&(*instance));
	XtAddCallback(instance->connect_rescan,
		XmNactivateCallback, doRescan,
		(XtPointer)&(*instance));
	XtAddCallback(instance->connect_cancel,
		XmNactivateCallback, connect_connect_cancel_CB1,
		(XtPointer)&(*instance));
return 0;
}

int 
dtb_connect_netunreach_initialize(DtbMessageData instance)
{
    if (instance->initialized)
    {
        return 0;
    }
    instance->initialized = True;

    instance->type = XmDIALOG_ERROR;
    instance->title = XmStringCreateLocalized("Connect");
    instance->message = XmStringCreateLocalized("Network is unreachable.");
    instance->action1_label = (XmString) NULL;
    instance->action1_callback = (XtCallbackProc) NULL;
    instance->action2_label = (XmString) NULL;
    instance->action2_callback = (XtCallbackProc) NULL;
    instance->action3_label = (XmString) NULL;
    instance->action3_callback = (XtCallbackProc) NULL;
    instance->cancel_button = True;
    instance->cancel_callback = (XtCallbackProc) NULL;
    instance->help_button = False;
    instance->help_data.help_text = (char *) NULL;
    instance->help_data.help_volume = "";
    instance->help_data.help_locationID = "";
    instance->default_button = DTB_CANCEL_BUTTON;
    return 0;
}

int 
dtb_connect_noderesponse_initialize(DtbMessageData instance)
{
    if (instance->initialized)
    {
        return 0;
    }
    instance->initialized = True;

    instance->type = XmDIALOG_ERROR;
    instance->title = XmStringCreateLocalized("Connect");
    instance->message = XmStringCreateLocalized("Node does not respond.");
    instance->action1_label = (XmString) NULL;
    instance->action1_callback = (XtCallbackProc) NULL;
    instance->action2_label = XmStringCreateLocalized("Retry");
    instance->action2_callback = (XtCallbackProc) NULL;
    instance->action3_label = (XmString) NULL;
    instance->action3_callback = (XtCallbackProc) NULL;
    instance->cancel_button = True;
    instance->cancel_callback = (XtCallbackProc) NULL;
    instance->help_button = True;
    instance->help_data.help_text = (char *) NULL;
    instance->help_data.help_volume = "";
    instance->help_data.help_locationID = "";
    instance->default_button = DTB_CANCEL_BUTTON;
    return 0;
}



static int 
dtb_connect_connect_create(
    DtbConnectConnectInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Display	*display= (parent == NULL? NULL:XtDisplay(parent));
    Arg	args[8];	/* need 3 args (add 5 to be safe) */
    int	n = 0;
    
    if (instance->connect == NULL) {
        n = 0;
        XtSetArg(args[n], XmNallowShellResize, True);  ++n;
        XtSetArg(args[n], XmNtitle, "Connect");  ++n;
        XtSetArg(args[n], XmNbackground, dtb_cvt_string_to_pixel(parent, "white"));  ++n;
        instance->connect =
            XmCreateDialogShell(parent,
                "dtb_connect_connect", args, n);
    }
    if (instance->connect == NULL)
        return -1;

    if (instance->connect_shellform == NULL) {
        instance->connect_shellform =
            XtVaCreateWidget("dtb_connect_connect_shellform",
                xmFormWidgetClass,
                instance->connect,
                XmNnoResize, True,
                XmNdefaultPosition, False,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNbackground, dtb_cvt_string_to_pixel(instance->connect, "white"),
                NULL);
    }
    if (instance->connect_shellform == NULL)
        return -1;

    if (instance->connect_panedwin == NULL) {
        instance->connect_panedwin =
            XtVaCreateWidget("connect_panedwin",
                xmPanedWindowWidgetClass,
                instance->connect_shellform,
                XmNbottomOffset, 0,
                XmNbottomPosition, 100,
                XmNbottomAttachment, XmATTACH_POSITION,
                XmNrightOffset, 0,
                XmNrightPosition, 100,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 0,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 0,
                XmNtopPosition, 0,
                XmNtopAttachment, XmATTACH_POSITION,
                XmNsashWidth, 1,
                XmNsashHeight, 1,
                XmNspacing, 0,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNbackground, dtb_cvt_string_to_pixel(instance->connect_shellform, "white"),
                NULL);
    }
    if (instance->connect_panedwin == NULL)
        return -1;

    if (instance->connect_form == NULL) {
        instance->connect_form =
            XtVaCreateWidget("connect_form",
                xmFormWidgetClass,
                instance->connect_panedwin,
                XmNallowResize, True,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNresizePolicy, XmRESIZE_ANY,
                XmNbackground, dtb_cvt_string_to_pixel(instance->connect_panedwin, "white"),
                NULL);
    }
    if (instance->connect_form == NULL)
        return -1;

    return 0;
}



static int 
dtb_connect_dialog_button_panel_create(
    DtbConnectConnectInfo instance,
    Widget parent
)
{
    
    if (instance->dialog_button_panel == NULL) {
        instance->dialog_button_panel =
            XtVaCreateWidget("dialog_button_panel",
                xmFormWidgetClass,
                parent,
                XmNpaneMaximum, 48,
                XmNpaneMinimum, 48,
                XmNresizePolicy, XmRESIZE_GROW,
                XmNmarginHeight, 7,
                XmNmarginWidth, 7,
                XmNpositionIndex, 1,
                XmNheight, 48,
                NULL);
    }
    if (instance->dialog_button_panel == NULL)
        return -1;

    return 0;
}



static int 
dtb_connect_controlpane_create(
    DtbConnectConnectInfo instance,
    Widget parent
)
{
    
    if (instance->controlpane == NULL) {
        instance->controlpane =
            XtVaCreateWidget("controlpane",
                xmFormWidgetClass,
                parent,
                XmNbottomOffset, 0,
                XmNbottomAttachment, XmATTACH_FORM,
                XmNrightOffset, 0,
                XmNrightAttachment, XmATTACH_FORM,
                XmNleftOffset, 0,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 0,
                XmNtopAttachment, XmATTACH_FORM,
                XmNresizePolicy, XmRESIZE_GROW,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNheight, 95,
                XmNwidth, 381,
                XmNy, 40,
                XmNx, 59,
                NULL);
    }
    if (instance->controlpane == NULL)
        return -1;

    return 0;
}



static int 
dtb_connect_network_box_create(
    DtbConnectConnectInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Arg	args[21];	/* need 16 args (add 5 to be safe) */
    int	n = 0;
    
    if (instance->networkBox_rowcolumn == NULL) {
        instance->networkBox_rowcolumn =
            XtVaCreateWidget("networkBox_rowcolumn",
                xmRowColumnWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightAttachment, XmATTACH_NONE,
                XmNleftOffset, 5,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 10,
                XmNtopAttachment, XmATTACH_FORM,
                XmNpacking, XmPACK_TIGHT,
                XmNisHomogeneous, False,
                XmNadjustLast, True,
                XmNspacing, 0,
                XmNmarginWidth, 0,
                XmNmarginHeight, 0,
                XmNentryAlignment, XmALIGNMENT_END,
                XmNorientation, XmHORIZONTAL,
                XmNy, 20,
                XmNx, 45,
                NULL);
    }
    if (instance->networkBox_rowcolumn == NULL)
        return -1;

    if (instance->networkBox_menu == NULL) {
        n = 0;
        XtSetArg(args[n], XmNrowColumnType, XmMENU_PULLDOWN);  ++n;
        instance->networkBox_menu =
            XmCreatePulldownMenu(instance->networkBox_rowcolumn,
                "networkBox_menu", args, n);
    }
    if (instance->networkBox_menu == NULL)
        return -1;

    label_xmstring = XmStringCreateLocalized("Network:");
    if (instance->networkBox_label == NULL) {
        instance->networkBox_label =
            XtVaCreateWidget("networkBox_label",
                xmLabelWidgetClass,
                instance->networkBox_rowcolumn,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->networkBox_label == NULL)
        return -1;

    if (instance->networkBox == NULL) {
        n = 0;
        XtSetArg(args[n], XmNrowColumnType, XmMENU_OPTION);  ++n;
        XtSetArg(args[n], XmNspacing, 0);  ++n;
        XtSetArg(args[n], XmNsubMenuId, instance->networkBox_menu);  ++n;
        instance->networkBox =
            XmCreateOptionMenu(instance->networkBox_rowcolumn,
                "networkBox", args, n);
    }
    if (instance->networkBox == NULL)
        return -1;

    return 0;
}



static int 
dtb_connect_node_box_create(
    DtbConnectConnectInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Arg	args[25];	/* need 20 args (add 5 to be safe) */
    int	n = 0;
    
    if (instance->nodeBox_rowcolumn == NULL) {
        instance->nodeBox_rowcolumn =
            XtVaCreateWidget("nodeBox_rowcolumn",
                xmRowColumnWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightAttachment, XmATTACH_NONE,
                XmNleftOffset, 5,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_WIDGET,
                XmNadjustLast, True,
                XmNspacing, 0,
                XmNmarginWidth, 0,
                XmNmarginHeight, 0,
                XmNentryAlignment, XmALIGNMENT_END,
                XmNorientation, XmHORIZONTAL,
                XmNy, 51,
                XmNx, 5,
                NULL);
    }
    if (instance->nodeBox_rowcolumn == NULL)
        return -1;

    label_xmstring = XmStringCreateLocalized("Node:");
    if (instance->nodeBox_label == NULL) {
        instance->nodeBox_label =
            XtVaCreateWidget("nodeBox_label",
                xmLabelWidgetClass,
                instance->nodeBox_rowcolumn,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->nodeBox_label == NULL)
        return -1;

    if (instance->nodeBox == NULL) {
        n = 0;
        XtSetArg(args[n], XmNmaxLength, 80);  ++n;
        XtSetArg(args[n], XmNeditable, True);  ++n;
        XtSetArg(args[n], XmNcursorPositionVisible, True);  ++n;
        XtSetArg(args[n], XmNcolumns, 12);  ++n;
        instance->nodeBox =
            XmCreateTextField(instance->nodeBox_rowcolumn,
                "nodeBox", args, n);
    }
    if (instance->nodeBox == NULL)
        return -1;

    return 0;
}



static int 
dtb_connect_separator_create(
    DtbConnectConnectInfo instance,
    Widget parent
)
{
    
    if (instance->separator == NULL) {
        instance->separator =
            XtVaCreateWidget("separator",
                xmSeparatorWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 0,
                XmNrightAttachment, XmATTACH_FORM,
                XmNleftOffset, 0,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_WIDGET,
                XmNseparatorType, XmSHADOW_ETCHED_IN,
                XmNorientation, XmHORIZONTAL,
                XmNheight, 10,
                XmNy, 79,
                XmNx, 21,
                NULL);
    }
    if (instance->separator == NULL)
        return -1;

    return 0;
}



static int 
dtb_connect_connect_ok_create(
    DtbConnectConnectInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized("Ok");
    if (instance->connect_ok == NULL) {
        instance->connect_ok =
            XtVaCreateWidget("connect_ok",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 0,
                XmNrightPosition, 30,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 10,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, True,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNdefaultButtonShadowThickness, 1,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->connect_ok == NULL)
        return -1;

    return 0;
}



static int 
dtb_connect_connect_rescan_create(
    DtbConnectConnectInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized("Rescan");
    if (instance->connect_rescan == NULL) {
        instance->connect_rescan =
            XtVaCreateWidget("connect_rescan",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 0,
                XmNrightPosition, 60,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 40,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, True,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNdefaultButtonShadowThickness, 1,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->connect_rescan == NULL)
        return -1;

    return 0;
}



static int 
dtb_connect_connect_cancel_create(
    DtbConnectConnectInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized("Cancel");
    if (instance->connect_cancel == NULL) {
        instance->connect_cancel =
            XtVaCreateWidget("connect_cancel",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 0,
                XmNrightPosition, 90,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 70,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, True,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNdefaultButtonShadowThickness, 1,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->connect_cancel == NULL)
        return -1;

    return 0;
}

