/*
 * File: connect_ui.h
 * Contains: Declarations of module objects, user create procedures,
 *           and callbacks.
 *
 * This file was generated by dtcodegen, from module connect
 *
 *    ** DO NOT MODIFY BY HAND - ALL MODIFICATIONS WILL BE LOST **
 */
#ifndef _CONNECT_UI_H_
#define _CONNECT_UI_H_

#include <stdlib.h>
#include <X11/Intrinsic.h>
#include "dtb_utils.h"

/*
 * User Interface Objects
 */
/*
 * Shared data structures
 */

typedef struct
{
    Boolean	initialized;
    
    Widget	connect_manual;	/* object "connect_manual" */
    Widget	connect_manual_shellform;
    Widget	connect_manual_panedwin;
    Widget	connect_manual_form;
    
    Widget	dialog_button_panel;
    Widget	controlpane;
    
    Widget	networkBox_rowcolumn;	/* object "networkBox" */
    Widget	networkBox_menu;
    Widget	networkBox_label;
    Widget	networkBox;
    
    Widget	nodeBox_rowcolumn;	/* object "nodeBox" */
    Widget	nodeBox_label;
    Widget	nodeBox;
    
    Widget	separator;
    Widget	connect_ok;
    Widget	connect_rescan;
    Widget	connect_cancel;
} DtbConnectConnectManualInfoRec, *DtbConnectConnectManualInfo;

typedef struct
{
    Boolean	initialized;
    
    Widget	authDialog;	/* object "authDialog" */
    Widget	authDialog_shellform;
    Widget	authDialog_panedwin;
    Widget	authDialog_form;
    
    Widget	dialog_button_panel3;
    Widget	controlpane3;
    Widget	separator3;
    
    Widget	password_rowcolumn;	/* object "password" */
    Widget	password_label;
    Widget	password;
    
    Widget	pw_ok;
    Widget	pw_cancel;
} DtbConnectAuthDialogInfoRec, *DtbConnectAuthDialogInfo;



typedef struct
{
    Boolean	initialized;
    
    Widget	connect;	/* object "connect" */
    Widget	connect_shellform;
    Widget	connect_panedwin;
    Widget	connect_form;
    
    Widget	dialog_button_panel2;
    Widget	controlpane2;
    
    Widget	list_scrolledwin;	/* object "list" */
    Widget	list;
    
    Widget	separator2;
    Widget	con_ok;
    Widget	con_manual;
    Widget	con_cancel;
} DtbConnectConnectInfoRec, *DtbConnectConnectInfo;


extern DtbConnectConnectManualInfoRec dtb_connect_connect_manual;
extern DtbConnectAuthDialogInfoRec dtb_connect_auth_dialog;
extern DtbMessageDataRec dtb_connect_netunreach;
extern DtbMessageDataRec dtb_connect_noderesponse;
extern DtbConnectConnectInfoRec dtb_connect_connect;

/*
 * Structure Clear Procedures: These set the fields to NULL
 */
int dtbConnectConnectManualInfo_clear(DtbConnectConnectManualInfo instance);
int dtbConnectAuthDialogInfo_clear(DtbConnectAuthDialogInfo instance);
int dtbConnectConnectInfo_clear(DtbConnectConnectInfo instance);

/*
 * Structure Initialization Procedures: These create the widgets
 */
int dtb_connect_connect_manual_initialize(
    DtbConnectConnectManualInfo	instance,
    Widget	parent
);
int dtb_connect_auth_dialog_initialize(
    DtbConnectAuthDialogInfo	instance,
    Widget	parent
);
int dtb_connect_netunreach_initialize(DtbMessageData instance);
int dtb_connect_noderesponse_initialize(DtbMessageData instance);
int dtb_connect_connect_initialize(
    DtbConnectConnectInfo	instance,
    Widget	parent
);

/*
 * User Callbacks
 */
void connectOk(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void doRescan(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void doSAP(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);

/*
 * Connections
 */
void connect_connect_cancel_CB1(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void connect_con_ok_CB1(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void connect_con_cancel_CB1(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void connect_con_manual_CB1(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
#endif /* _CONNECT_UI_H_ */
