/*
 * File: deviceConfig_ui.c
 * Contains: user module object initialize and create functions
 *
 * This file was generated by dtcodegen, from module deviceConfig
 *
 *    ** DO NOT MODIFY BY HAND - ALL MODIFICATIONS WILL BE LOST **
 */


#include <stdlib.h>
#include <X11/Intrinsic.h>
#include <Xm/DialogS.h>
#include <Xm/Form.h>
#include <Xm/PanedW.h>
#include <Xm/Label.h>
#include <Xm/RowColumn.h>
#include <Xm/ScrollBar.h>
#include <Xm/ScrolledW.h>
#include <Xm/List.h>
#include <Xm/Separator.h>
#include <Xm/TextF.h>
#include <Xm/Text.h>
#include <Xm/PushB.h>
#include "dtb_utils.h"
#include "morsetutor.h"
#include "deviceConfig_ui.h"


DtbDeviceConfigDevConfigInfoRec	dtb_device_config_dev_config = 
{
    False	 /* initialized */
};

/*
 * Widget create procedure decls
 */
static int dtb_device_config_dev_config_create(
    DtbDeviceConfigDevConfigInfo	instance,
    Widget	parent
);
static int dtb_device_config_dialog_button_panel_create(
    DtbDeviceConfigDevConfigInfo	instance,
    Widget	parent
);
static int dtb_device_config_controlpane_create(
    DtbDeviceConfigDevConfigInfo	instance,
    Widget	parent
);
static int dtb_device_config_label_create(
    DtbDeviceConfigDevConfigInfo	instance,
    Widget	parent
);
static int dtb_device_config_call_create(
    DtbDeviceConfigDevConfigInfo	instance,
    Widget	parent
);
static int dtb_device_config_devkey_create(
    DtbDeviceConfigDevConfigInfo	instance,
    Widget	parent
);
static int dtb_device_config_devname_create(
    DtbDeviceConfigDevConfigInfo	instance,
    Widget	parent
);
static int dtb_device_config_separator_create(
    DtbDeviceConfigDevConfigInfo	instance,
    Widget	parent
);
static int dtb_device_config_devconf_ok_create(
    DtbDeviceConfigDevConfigInfo	instance,
    Widget	parent
);
static int dtb_device_config_devconf_cancel_create(
    DtbDeviceConfigDevConfigInfo	instance,
    Widget	parent
);

int 
dtbDeviceConfigDevConfigInfo_clear(DtbDeviceConfigDevConfigInfo instance)
{
    memset((void *)(instance), 0, sizeof(*instance));
    return 0;
}

int 
dtb_device_config_dev_config_initialize(
    DtbDeviceConfigDevConfigInfo instance,
    Widget parent
)
{
    WidgetList	children = NULL;
    int		numChildren = 0;
    if (instance->initialized)
    {
        return 0;
    }
    instance->initialized = True;

    dtb_device_config_dev_config_create(instance,
        parent);
    dtb_device_config_dialog_button_panel_create(instance,
        instance->devConfig_panedwin);
    dtb_device_config_controlpane_create(instance,
        instance->devConfig_form);
    dtb_device_config_label_create(instance,
        instance->controlpane);
    dtb_device_config_call_create(instance,
        instance->controlpane);
    dtb_device_config_devkey_create(instance,
        instance->controlpane);
    dtb_device_config_devname_create(instance,
        instance->controlpane);
    dtb_device_config_separator_create(instance,
        instance->controlpane);
    dtb_device_config_devconf_ok_create(instance,
        instance->dialog_button_panel);
    dtb_device_config_devconf_cancel_create(instance,
        instance->dialog_button_panel);
    
    /*
     * Add widget-reference resources.
     */
    
    XtVaSetValues(instance->devConfig_shellform,
        XmNdefaultButton, instance->devconf_ok,
        NULL);
    
    XtVaSetValues(instance->call_rowcolumn,
        XmNtopWidget, instance->devname_rowcolumn,
        NULL);
    
    XtVaSetValues(instance->devkey_scrolledwin,
        XmNtopWidget, instance->label,
        NULL);
    
    XtVaSetValues(instance->devname_rowcolumn,
        XmNtopWidget, instance->devkey_scrolledwin,
        NULL);
    
    XtVaSetValues(instance->separator,
        XmNtopWidget, instance->call_rowcolumn,
        NULL);
    
    /*
     * Call utility functions to do group layout
     */
    
    /*
     * Make Dialog Button-Panel & Footer a fixed height
     */
    {
        Dimension	pane_height;

        XtVaGetValues(instance->dialog_button_panel,
            XmNheight, &pane_height,
            NULL);
        XtVaSetValues(instance->dialog_button_panel,
            XmNpaneMinimum,   pane_height,
            XmNpaneMaximum,   pane_height,
            NULL);

    }
    
    /*
     * Manage the tree, from the bottom up.
     */
    XtVaGetValues(instance->call_rowcolumn,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtManageChild(instance->devkey);
    XtVaGetValues(instance->devname_rowcolumn,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->controlpane,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->devConfig_form,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->dialog_button_panel,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtManageChild(instance->devConfig_form);
    XtManageChild(instance->dialog_button_panel);
    XtVaGetValues(instance->devConfig_shellform,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    /*
     * Turn off traversal for invisible sash in dialog's PanedWindow
     */
    dtb_remove_sash_focus(instance->devConfig_panedwin);
    
    /*
     * Add User and Connection callbacks
     */
    	XtAddCallback(instance->devconf_ok,
		XmNactivateCallback, deviceConfig_devconf_ok_CB1,
    		(XtPointer)&(*instance));
	XtAddCallback(instance->devconf_cancel,
		XmNactivateCallback, deviceConfig_devconf_cancel_CB1,
		(XtPointer)&(*instance));
return 0;
}



static int 
dtb_device_config_dev_config_create(
    DtbDeviceConfigDevConfigInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Display	*display= (parent == NULL? NULL:XtDisplay(parent));
    Arg	args[8];	/* need 3 args (add 5 to be safe) */
    int	n = 0;
    
    if (instance->devConfig == NULL) {
        n = 0;
        XtSetArg(args[n], XmNallowShellResize, True);  ++n;
        XtSetArg(args[n], XmNtitle, "Device Config");  ++n;
        XtSetArg(args[n], XmNbackground, dtb_cvt_string_to_pixel(parent, "white"));  ++n;
        instance->devConfig =
            XmCreateDialogShell(parent,
                "dtb_deviceConfig_devConfig", args, n);
    }
    if (instance->devConfig == NULL)
        return -1;

    if (instance->devConfig_shellform == NULL) {
        instance->devConfig_shellform =
            XtVaCreateWidget("dtb_deviceConfig_devConfig_shellform",
                xmFormWidgetClass,
                instance->devConfig,
                XmNnoResize, True,
                XmNdefaultPosition, False,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNbackground, dtb_cvt_string_to_pixel(instance->devConfig, "white"),
                NULL);
    }
    if (instance->devConfig_shellform == NULL)
        return -1;

    if (instance->devConfig_panedwin == NULL) {
        instance->devConfig_panedwin =
            XtVaCreateWidget("devConfig_panedwin",
                xmPanedWindowWidgetClass,
                instance->devConfig_shellform,
                XmNbottomOffset, 0,
                XmNbottomPosition, 100,
                XmNbottomAttachment, XmATTACH_POSITION,
                XmNrightOffset, 0,
                XmNrightPosition, 100,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 0,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 0,
                XmNtopPosition, 0,
                XmNtopAttachment, XmATTACH_POSITION,
                XmNsashWidth, 1,
                XmNsashHeight, 1,
                XmNspacing, 0,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNbackground, dtb_cvt_string_to_pixel(instance->devConfig_shellform, "white"),
                NULL);
    }
    if (instance->devConfig_panedwin == NULL)
        return -1;

    if (instance->devConfig_form == NULL) {
        instance->devConfig_form =
            XtVaCreateWidget("devConfig_form",
                xmFormWidgetClass,
                instance->devConfig_panedwin,
                XmNallowResize, True,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNresizePolicy, XmRESIZE_ANY,
                XmNbackground, dtb_cvt_string_to_pixel(instance->devConfig_panedwin, "white"),
                NULL);
    }
    if (instance->devConfig_form == NULL)
        return -1;

    return 0;
}



static int 
dtb_device_config_dialog_button_panel_create(
    DtbDeviceConfigDevConfigInfo instance,
    Widget parent
)
{
    
    if (instance->dialog_button_panel == NULL) {
        instance->dialog_button_panel =
            XtVaCreateWidget("dialog_button_panel",
                xmFormWidgetClass,
                parent,
                XmNpaneMaximum, 48,
                XmNpaneMinimum, 48,
                XmNresizePolicy, XmRESIZE_GROW,
                XmNmarginHeight, 7,
                XmNmarginWidth, 7,
                XmNpositionIndex, 1,
                XmNheight, 48,
                NULL);
    }
    if (instance->dialog_button_panel == NULL)
        return -1;

    return 0;
}



static int 
dtb_device_config_controlpane_create(
    DtbDeviceConfigDevConfigInfo instance,
    Widget parent
)
{
    
    if (instance->controlpane == NULL) {
        instance->controlpane =
            XtVaCreateWidget("controlpane",
                xmFormWidgetClass,
                parent,
                XmNbottomOffset, 0,
                XmNbottomAttachment, XmATTACH_FORM,
                XmNrightOffset, 0,
                XmNrightAttachment, XmATTACH_FORM,
                XmNleftOffset, 0,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 0,
                XmNtopAttachment, XmATTACH_FORM,
                XmNresizePolicy, XmRESIZE_GROW,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNheight, 247,
                XmNwidth, 380,
                XmNy, 0,
                XmNx, 0,
                NULL);
    }
    if (instance->controlpane == NULL)
        return -1;

    return 0;
}



static int 
dtb_device_config_label_create(
    DtbDeviceConfigDevConfigInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized("Device Key:");
    if (instance->label == NULL) {
        instance->label =
            XtVaCreateWidget("label",
                xmLabelWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightAttachment, XmATTACH_NONE,
                XmNleftOffset, 5,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 10,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, True,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNy, 13,
                XmNx, 22,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->label == NULL)
        return -1;

    return 0;
}



static int 
dtb_device_config_call_create(
    DtbDeviceConfigDevConfigInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Arg	args[25];	/* need 20 args (add 5 to be safe) */
    int	n = 0;
    
    if (instance->call_rowcolumn == NULL) {
        instance->call_rowcolumn =
            XtVaCreateWidget("call_rowcolumn",
                xmRowColumnWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightAttachment, XmATTACH_NONE,
                XmNleftOffset, 5,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_WIDGET,
                XmNadjustLast, True,
                XmNspacing, 0,
                XmNmarginWidth, 0,
                XmNmarginHeight, 0,
                XmNentryAlignment, XmALIGNMENT_BEGINNING,
                XmNorientation, XmVERTICAL,
                XmNy, 158,
                XmNx, 16,
                NULL);
    }
    if (instance->call_rowcolumn == NULL)
        return -1;

    label_xmstring = XmStringCreateLocalized("Call: ");
    if (instance->call_label == NULL) {
        instance->call_label =
            XtVaCreateWidget("call_label",
                xmLabelWidgetClass,
                instance->call_rowcolumn,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->call_label == NULL)
        return -1;

    if (instance->call == NULL) {
        n = 0;
        XtSetArg(args[n], XmNmaxLength, 8);  ++n;
        XtSetArg(args[n], XmNeditable, True);  ++n;
        XtSetArg(args[n], XmNcursorPositionVisible, True);  ++n;
        XtSetArg(args[n], XmNcolumns, 8);  ++n;
        instance->call =
            XmCreateTextField(instance->call_rowcolumn,
                "call", args, n);
    }
    if (instance->call == NULL)
        return -1;

    return 0;
}



static int 
dtb_device_config_devkey_create(
    DtbDeviceConfigDevConfigInfo instance,
    Widget parent
)
{
    Arg	args[24];	/* need 19 args (add 5 to be safe) */
    int	n = 0;
    
    if (instance->devkey == NULL) {
        n = 0;
        XtSetArg(args[n], XmNbottomAttachment, XmATTACH_NONE);  ++n;
        XtSetArg(args[n], XmNrightAttachment, XmATTACH_NONE);  ++n;
        XtSetArg(args[n], XmNleftOffset, 5);  ++n;
        XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM);  ++n;
        XtSetArg(args[n], XmNtopOffset, 5);  ++n;
        XtSetArg(args[n], XmNtopAttachment, XmATTACH_WIDGET);  ++n;
        XtSetArg(args[n], XmNscrollBarDisplayPolicy, XmAUTOMATIC);  ++n;
        XtSetArg(args[n], XmNvisualPolicy, XmVARIABLE);  ++n;
        XtSetArg(args[n], XmNscrollingPolicy, XmAPPLICATION_DEFINED);  ++n;
        XtSetArg(args[n], XmNy, 39);  ++n;
        XtSetArg(args[n], XmNx, 15);  ++n;
        XtSetArg(args[n], XmNwordWrap, True);  ++n;
        XtSetArg(args[n], XmNeditMode, XmMULTI_LINE_EDIT);  ++n;
        XtSetArg(args[n], XmNscrollHorizontal, False);  ++n;
        XtSetArg(args[n], XmNscrollVertical, True);  ++n;
        XtSetArg(args[n], XmNcolumns, 32);  ++n;
        XtSetArg(args[n], XmNrows, 4);  ++n;
        XtSetArg(args[n], XmNcursorPositionVisible, True);  ++n;
        XtSetArg(args[n], XmNeditable, True);  ++n;
        instance->devkey =
            XmCreateScrolledText(parent,
                "devkey", args, n);
    }
    instance->devkey_scrolledwin = XtParent(instance->devkey);
    return 0;
}



static int 
dtb_device_config_devname_create(
    DtbDeviceConfigDevConfigInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Arg	args[26];	/* need 21 args (add 5 to be safe) */
    int	n = 0;
    
    if (instance->devname_rowcolumn == NULL) {
        instance->devname_rowcolumn =
            XtVaCreateWidget("devname_rowcolumn",
                xmRowColumnWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightAttachment, XmATTACH_NONE,
                XmNleftOffset, 5,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_WIDGET,
                XmNadjustLast, True,
                XmNspacing, 0,
                XmNmarginWidth, 0,
                XmNmarginHeight, 0,
                XmNentryAlignment, XmALIGNMENT_BEGINNING,
                XmNorientation, XmVERTICAL,
                XmNy, 159,
                XmNx, 11,
                NULL);
    }
    if (instance->devname_rowcolumn == NULL)
        return -1;

    label_xmstring = XmStringCreateLocalized("Device Name: ");
    if (instance->devname_label == NULL) {
        instance->devname_label =
            XtVaCreateWidget("devname_label",
                xmLabelWidgetClass,
                instance->devname_rowcolumn,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->devname_label == NULL)
        return -1;

    if (instance->devname == NULL) {
        n = 0;
        XtSetArg(args[n], XmNvalue, "Telegraphy");  ++n;
        XtSetArg(args[n], XmNmaxLength, 40);  ++n;
        XtSetArg(args[n], XmNeditable, True);  ++n;
        XtSetArg(args[n], XmNcursorPositionVisible, True);  ++n;
        XtSetArg(args[n], XmNcolumns, 30);  ++n;
        instance->devname =
            XmCreateTextField(instance->devname_rowcolumn,
                "devname", args, n);
    }
    if (instance->devname == NULL)
        return -1;

    return 0;
}



static int 
dtb_device_config_separator_create(
    DtbDeviceConfigDevConfigInfo instance,
    Widget parent
)
{
    
    if (instance->separator == NULL) {
        instance->separator =
            XtVaCreateWidget("separator",
                xmSeparatorWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 0,
                XmNrightAttachment, XmATTACH_FORM,
                XmNleftOffset, 0,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_WIDGET,
                XmNseparatorType, XmSHADOW_ETCHED_IN,
                XmNorientation, XmHORIZONTAL,
                XmNheight, 10,
                XmNy, 250,
                XmNx, 35,
                NULL);
    }
    if (instance->separator == NULL)
        return -1;

    return 0;
}



static int 
dtb_device_config_devconf_ok_create(
    DtbDeviceConfigDevConfigInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized("OK");
    if (instance->devconf_ok == NULL) {
        instance->devconf_ok =
            XtVaCreateWidget("devconf_ok",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 0,
                XmNrightPosition, 40,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 20,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, True,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNdefaultButtonShadowThickness, 1,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->devconf_ok == NULL)
        return -1;

    return 0;
}



static int 
dtb_device_config_devconf_cancel_create(
    DtbDeviceConfigDevConfigInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized("Cancel");
    if (instance->devconf_cancel == NULL) {
        instance->devconf_cancel =
            XtVaCreateWidget("devconf_cancel",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 0,
                XmNrightPosition, 80,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 60,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, True,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNdefaultButtonShadowThickness, 1,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->devconf_cancel == NULL)
        return -1;

    return 0;
}

