/*
 * File: deviceConfig_ui.h
 * Contains: Declarations of module objects, user create procedures,
 *           and callbacks.
 *
 * This file was generated by dtcodegen, from module deviceConfig
 *
 *    ** DO NOT MODIFY BY HAND - ALL MODIFICATIONS WILL BE LOST **
 */
#ifndef _DEVICECONFIG_UI_H_
#define _DEVICECONFIG_UI_H_

#include <stdlib.h>
#include <X11/Intrinsic.h>
#include "dtb_utils.h"

/*
 * User Interface Objects
 */
/*
 * Shared data structures
 */

typedef struct
{
    Boolean	initialized;
    
    Widget	devConfig;	/* object "devConfig" */
    Widget	devConfig_shellform;
    Widget	devConfig_panedwin;
    Widget	devConfig_form;
    
    Widget	dialog_button_panel;
    Widget	controlpane;
    Widget	label;
    
    Widget	call_rowcolumn;	/* object "call" */
    Widget	call_label;
    Widget	call;
    
    Widget	devkey_scrolledwin;	/* object "devkey" */
    Widget	devkey;
    
    Widget	devname_rowcolumn;	/* object "devname" */
    Widget	devname_label;
    Widget	devname;
    
    Widget	separator;
    Widget	devconf_ok;
    Widget	devconf_cancel;
} DtbDeviceConfigDevConfigInfoRec, *DtbDeviceConfigDevConfigInfo;


extern DtbDeviceConfigDevConfigInfoRec dtb_device_config_dev_config;

/*
 * Structure Clear Procedures: These set the fields to NULL
 */
int dtbDeviceConfigDevConfigInfo_clear(DtbDeviceConfigDevConfigInfo instance);

/*
 * Structure Initialization Procedures: These create the widgets
 */
int dtb_device_config_dev_config_initialize(
    DtbDeviceConfigDevConfigInfo	instance,
    Widget	parent
);

/*
 * User Callbacks
 */

/*
 * Connections
 */
void deviceConfig_devconf_ok_CB1(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
void deviceConfig_devconf_cancel_CB1(
    Widget	widget,
    XtPointer	clientData,
    XtPointer	callData
);
#endif /* _DEVICECONFIG_UI_H_ */
