/*** DTB_USER_CODE_START vvv Add file header below vvv ***/
/*** DTB_USER_CODE_END   ^^^ Add file header above ^^^ ***/

/*
 * File: main_stubs.c
 * Contains: Module callbacks and connection functions
 *
 * This file was generated by dtcodegen, from module main
 *
 * Any text may be added between the DTB_USER_CODE_START and
 * DTB_USER_CODE_END comments (even non-C code). Descriptive comments
 * are provided only as an aid.
 *
 *  ** EDIT ONLY WITHIN SECTIONS MARKED WITH DTB_USER_CODE COMMENTS.  **
 *  ** ALL OTHER MODIFICATIONS WILL BE OVERWRITTEN. DO NOT MODIFY OR  **
 *  ** DELETE THE GENERATED COMMENTS!                                 **
 */

#include <stdio.h>
#include <Xm/Xm.h>
#include "dtb_utils.h"
#include "main_ui.h"

/*
 * Header files for cross-module connections
 */
#include "main_ui.h"


/**************************************************************************
 *** DTB_USER_CODE_START
 ***
 *** All necessary header files have been included.
 ***
 *** Add include files, types, macros, externs, and user functions here.
 ***/
#include "configuration.h"
#include "connect_ui.h"
#include "settings_ui.h"
#include "charset_ui.h"

/*** DTB_USER_CODE_END
 ***
 *** End of user code section
 ***
 **************************************************************************/



void 
main_about_ok_CB1(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    DtbMainAboutInfo	dtbTarget = (DtbMainAboutInfo)clientData;
    DtbMainAboutInfo	instance = dtbTarget;	/* obsolete */
    
    if (!(dtbTarget->initialized))
    {
        dtb_main_about_initialize(dtbTarget, dtb_main_mainwindow.mainwindow);
    }
    XtUnmanageChild(instance->about_shellform);
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/

    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
main_Help_menu_items_item_CB1(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    DtbMainAboutInfo	dtbTarget = (DtbMainAboutInfo)clientData;
    DtbMainAboutInfo	instance = dtbTarget;	/* obsolete */
    
    if (!(dtbTarget->initialized))
    {
        dtb_main_about_initialize(dtbTarget, dtb_main_mainwindow.mainwindow);
    }
    XtManageChild(instance->about_shellform);
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/

    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
doConnect(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/

	DtbConnectConnectInfo dtbTarget = (DtbConnectConnectInfo)&dtb_connect_connect;

    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/



	if (!(dtbTarget->initialized))
	{
		dtb_connect_connect_initialize(dtbTarget, dtb_main_mainwindow.mainwindow);
	}
	XtVaSetValues(dtbTarget->connect_shellform, XmNdialogStyle, XmDIALOG_FULL_APPLICATION_MODAL, NULL);
	XtManageChild(dtbTarget->connect_shellform);

    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
startTraining(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
pauseTraining(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
stopTraining(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
doQuit(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
	exit(0);
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
showSpeed(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
	DtbSettingsSpeedDialogInfo dtbTarget = (DtbSettingsSpeedDialogInfo)&dtb_settings_speed_dialog;

    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/

	if (!(dtbTarget->initialized))
	{
		dtb_settings_speed_dialog_initialize(dtbTarget, dtb_main_mainwindow.mainwindow);
	}
	XtVaSetValues(dtbTarget->speedDialog_shellform, XmNdialogStyle, XmDIALOG_FULL_APPLICATION_MODAL, NULL);
	XtManageChild(dtbTarget->speedDialog_shellform);

    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
showCharset(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
	DtbCharsetCharsetDialogInfo dtbTarget = (DtbCharsetCharsetDialogInfo)&dtb_charset_charset_dialog;

    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/

	if (!(dtbTarget->initialized))
	{
		dtb_charset_charset_dialog_initialize(dtbTarget, dtb_main_mainwindow.mainwindow);
	}
	XtVaSetValues(dtbTarget->charsetDialog_shellform, XmNdialogStyle, XmDIALOG_FULL_APPLICATION_MODAL, NULL);
	XtManageChild(dtbTarget->charsetDialog_shellform);

    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
showCode(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
	DtbSettingsCodeDialogInfo dtbTarget = (DtbSettingsCodeDialogInfo)&dtb_settings_code_dialog;
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/

	if (!(dtbTarget->initialized))
	{
		dtb_settings_code_dialog_initialize(dtbTarget, dtb_main_mainwindow.mainwindow);
	}
	XtVaSetValues(dtbTarget->codeDialog_shellform, XmNdialogStyle, XmDIALOG_FULL_APPLICATION_MODAL, NULL);
	XtManageChild(dtbTarget->codeDialog_shellform);

    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
sendToSounder(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
	vConfiguration.sounderSelected = !vConfiguration.sounderSelected;
	if (vConfiguration.sounderSelected) {
		dtb_set_label_from_image_file(dtb_main_mainwindow.sounderButton, "sounder_r.m");
	} else {
		dtb_set_label_from_image_file(dtb_main_mainwindow.sounderButton, "sounder.m");
	}
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
sendToRadio(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
	vConfiguration.radioSelected = !vConfiguration.radioSelected;
	if (vConfiguration.radioSelected) {
		dtb_set_label_from_image_file(dtb_main_mainwindow.sendButton, "send_r.m");
	} else {
		dtb_set_label_from_image_file(dtb_main_mainwindow.sendButton, "send.m");
	}
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}



/**************************************************************************
 *** DTB_USER_CODE_START
 ***
 *** All automatically-generated data and functions have been defined.
 ***
 *** Add new functions here, or at the top of the file.
 ***/

/*** DTB_USER_CODE_END
 ***
 *** End of user code section
 ***
 **************************************************************************/


