/*
 * File: main_ui.c
 * Contains: user module object initialize and create functions
 *
 * This file was generated by dtcodegen, from module main
 *
 *    ** DO NOT MODIFY BY HAND - ALL MODIFICATIONS WILL BE LOST **
 */


#include <stdlib.h>
#include <X11/Intrinsic.h>
#include <X11/Shell.h>
#include <Xm/DialogS.h>
#include <Xm/MenuShell.h>
#include <Xm/RowColumn.h>
#include <Xm/PanedW.h>
#include <Xm/MainW.h>
#include <Xm/Form.h>
#include <Xm/CascadeB.h>
#include <Xm/PushB.h>
#include <Xm/Separator.h>
#include <Xm/Text.h>
#include <Xm/ScrollBar.h>
#include <Xm/ScrolledW.h>
#include <Xm/List.h>
#include <Xm/Label.h>
#include "dtb_utils.h"
#include "morsetutor.h"
#include "main_ui.h"


DtbMainMainwindowInfoRec	dtb_main_mainwindow = 
{
    False	 /* initialized */
};

DtbMainAboutInfoRec	dtb_main_about = 
{
    False	 /* initialized */
};

/*
 * Widget create procedure decls
 */
static int dtb_main_mainwindow_create(
    DtbMainMainwindowInfo	instance,
    Widget	parent
);
static int dtb_main_about_create(
    DtbMainAboutInfo	instance,
    Widget	parent
);
static int dtb_main_menubar_create(
    DtbMainMainwindowInfo	instance,
    Widget	parent
);
static int dtb_main_mainwindow_toolbar_create(
    DtbMainMainwindowInfo	instance,
    Widget	parent
);
static int dtb_main_menubar_file_item_file_menu_create(
    DtbMainMainwindowInfo	instance,
    Widget	parent
);
static int dtb_main_menubar_edit_item_edit_menu_create(
    DtbMainMainwindowInfo	instance,
    Widget	parent
);
static int dtb_main_menubar_training_item_training_menu_create(
    DtbMainMainwindowInfo	instance,
    Widget	parent
);
static int dtb_main_menubar_help_item_help_menu_create(
    DtbMainMainwindowInfo	instance,
    Widget	parent
);
static int dtb_main_connect_button_create(
    DtbMainMainwindowInfo	instance,
    Widget	parent
);
static int dtb_main_start_button_create(
    DtbMainMainwindowInfo	instance,
    Widget	parent
);
static int dtb_main_pause_button_create(
    DtbMainMainwindowInfo	instance,
    Widget	parent
);
static int dtb_main_stop_button_create(
    DtbMainMainwindowInfo	instance,
    Widget	parent
);
static int dtb_main_sounder_button_create(
    DtbMainMainwindowInfo	instance,
    Widget	parent
);
static int dtb_main_send_button_create(
    DtbMainMainwindowInfo	instance,
    Widget	parent
);
static int dtb_main_rx_box_create(
    DtbMainMainwindowInfo	instance,
    Widget	parent
);
static int dtb_main_output_box_create(
    DtbMainMainwindowInfo	instance,
    Widget	parent
);
static int dtb_main_dialog_button_panel_create(
    DtbMainAboutInfo	instance,
    Widget	parent
);
static int dtb_main_controlpane_create(
    DtbMainAboutInfo	instance,
    Widget	parent
);
static int dtb_main_label_create(
    DtbMainAboutInfo	instance,
    Widget	parent
);
static int dtb_main_about_ok_create(
    DtbMainAboutInfo	instance,
    Widget	parent
);

int 
dtbMainMainwindowInfo_clear(DtbMainMainwindowInfo instance)
{
    memset((void *)(instance), 0, sizeof(*instance));
    return 0;
}

int 
dtb_main_mainwindow_initialize(
    DtbMainMainwindowInfo instance,
    Widget parent
)
{
    WidgetList	children = NULL;
    int		numChildren = 0;
    if (instance->initialized)
    {
        return 0;
    }
    instance->initialized = True;

    dtb_main_mainwindow_create(instance,
        parent);
    dtb_main_menubar_create(instance,
        instance->mainwindow_mainwin);
    dtb_main_mainwindow_toolbar_create(instance,
        instance->mainwindow_mainwin);
    dtb_main_menubar_file_item_file_menu_create(instance,
        instance->menubar);
    dtb_main_menubar_edit_item_edit_menu_create(instance,
        instance->menubar);
    dtb_main_menubar_training_item_training_menu_create(instance,
        instance->menubar);
    dtb_main_menubar_help_item_help_menu_create(instance,
        instance->menubar);
    dtb_main_connect_button_create(instance,
        instance->mainwindow_toolbar);
    dtb_main_start_button_create(instance,
        instance->mainwindow_toolbar);
    dtb_main_pause_button_create(instance,
        instance->mainwindow_toolbar);
    dtb_main_stop_button_create(instance,
        instance->mainwindow_toolbar);
    dtb_main_sounder_button_create(instance,
        instance->mainwindow_toolbar);
    dtb_main_send_button_create(instance,
        instance->mainwindow_toolbar);
    dtb_main_rx_box_create(instance,
        instance->mainwindow_form);
    dtb_main_output_box_create(instance,
        instance->mainwindow_form);
    
    /*
     * Add widget-reference resources.
     */
    
    XtVaSetValues(instance->mainwindow_mainwin,
        XmNcommandWindow, instance->mainwindow_toolbar,
        XmNmenuBar, instance->menubar,
        XmNworkWindow, instance->mainwindow_form,
        NULL);
    
    XtVaSetValues(instance->menubar,
        XmNmenuHelpWidget, instance->menubar_items.Help_item,
        NULL);
    XtVaSetValues(instance->menubar_items.File_item,
        XmNsubMenuId, instance->menubar_File_item_File_menu,
        NULL);
    XtVaSetValues(instance->menubar_items.Edit_item,
        XmNsubMenuId, instance->menubar_Edit_item_Edit_menu,
        NULL);
    XtVaSetValues(instance->menubar_items.Training_item,
        XmNsubMenuId, instance->menubar_Training_item_Training_menu,
        NULL);
    XtVaSetValues(instance->menubar_items.Help_item,
        XmNsubMenuId, instance->menubar_Help_item_Help_menu,
        NULL);
    
    XtVaSetValues(instance->startButton,
        XmNleftWidget, instance->connectButton,
        NULL);
    
    XtVaSetValues(instance->pauseButton,
        XmNleftWidget, instance->startButton,
        NULL);
    
    XtVaSetValues(instance->stopButton,
        XmNleftWidget, instance->pauseButton,
        NULL);
    
    XtVaSetValues(instance->sounderButton,
        XmNleftWidget, instance->stopButton,
        NULL);
    
    XtVaSetValues(instance->sendButton,
        XmNleftWidget, instance->sounderButton,
        NULL);
    
    XtVaSetValues(instance->outputBox_scrolledwin,
        XmNbottomWidget, instance->rxBox,
        NULL);
    
    /*
     * Call utility functions to do group layout
     */
    
    XmMainWindowSetAreas(instance->mainwindow_mainwin,
        instance->menubar,
        instance->mainwindow_toolbar,
        NULL,
        NULL,
        instance->mainwindow_form);
    
    /*
     * Manage the tree, from the bottom up.
     */
    XtVaGetValues(instance->menubar_File_item_File_menu,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->menubar_Edit_item_Edit_menu,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->menubar_Training_item_Training_menu,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->menubar_Help_item_Help_menu,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->menubar,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->mainwindow_toolbar,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtManageChild(instance->outputBox);
    XtVaGetValues(instance->mainwindow_form,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtManageChild(instance->menubar);
    XtManageChild(instance->mainwindow_toolbar);
    XtManageChild(instance->mainwindow_form);
    XtVaGetValues(instance->mainwindow,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    
    /*
     * Add User and Connection callbacks
     */
    	XtAddCallback(instance->mainwindow,
		XmNdestroyCallback, doQuit,
    		(XtPointer)&(*instance));
	XtAddCallback(instance->menubar_File_item_File_menu_items.items_item,
		XmNactivateCallback, doConnect,
		(XtPointer)&(*instance));
	XtAddCallback(instance->menubar_File_item_File_menu_items.Quit_item,
		XmNactivateCallback, doQuit,
		(XtPointer)&(*instance));
	XtAddCallback(instance->menubar_Edit_item_Edit_menu_items.items_item,
		XmNactivateCallback, showSpeed,
		(XtPointer)&(*instance));
	XtAddCallback(instance->menubar_Edit_item_Edit_menu_items.items_item2,
		XmNactivateCallback, showCharset,
		(XtPointer)&(*instance));
	XtAddCallback(instance->menubar_Edit_item_Edit_menu_items.items_item3,
		XmNactivateCallback, showCode,
		(XtPointer)&(*instance));
	XtAddCallback(instance->menubar_Training_item_Training_menu_items.Start_item,
		XmNactivateCallback, startTraining,
		(XtPointer)&(*instance));
	XtAddCallback(instance->menubar_Help_item_Help_menu_items.items_item,
		XmNactivateCallback, main_Help_menu_items_item_CB1,
		(XtPointer)&dtb_main_about);
	XtAddCallback(instance->connectButton,
		XmNactivateCallback, doConnect,
		(XtPointer)&(*instance));
	XtAddCallback(instance->startButton,
		XmNactivateCallback, startTraining,
		(XtPointer)&(*instance));
	XtAddCallback(instance->pauseButton,
		XmNactivateCallback, pauseTraining,
		(XtPointer)&(*instance));
	XtAddCallback(instance->stopButton,
		XmNactivateCallback, stopTraining,
		(XtPointer)&(*instance));
	XtAddCallback(instance->sounderButton,
		XmNactivateCallback, sendToSounder,
		(XtPointer)&(*instance));
	XtAddCallback(instance->sendButton,
		XmNactivateCallback, sendToRadio,
		(XtPointer)&(*instance));
return 0;
}

int 
dtbMainAboutInfo_clear(DtbMainAboutInfo instance)
{
    memset((void *)(instance), 0, sizeof(*instance));
    return 0;
}

int 
dtb_main_about_initialize(
    DtbMainAboutInfo instance,
    Widget parent
)
{
    WidgetList	children = NULL;
    int		numChildren = 0;
    if (instance->initialized)
    {
        return 0;
    }
    instance->initialized = True;

    dtb_main_about_create(instance,
        parent);
    dtb_main_dialog_button_panel_create(instance,
        instance->about_panedwin);
    dtb_main_controlpane_create(instance,
        instance->about_form);
    dtb_main_label_create(instance,
        instance->controlpane);
    dtb_main_about_ok_create(instance,
        instance->dialog_button_panel);
    
    /*
     * Add widget-reference resources.
     */
    
    XtVaSetValues(instance->about_shellform,
        XmNdefaultButton, instance->about_ok,
        NULL);
    
    /*
     * Call utility functions to do group layout
     */
    
    /*
     * Make Dialog Button-Panel & Footer a fixed height
     */
    {
        Dimension	pane_height;

        XtVaGetValues(instance->dialog_button_panel,
            XmNheight, &pane_height,
            NULL);
        XtVaSetValues(instance->dialog_button_panel,
            XmNpaneMinimum,   pane_height,
            XmNpaneMaximum,   pane_height,
            NULL);

    }
    
    /*
     * Manage the tree, from the bottom up.
     */
    XtVaGetValues(instance->controlpane,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->about_form,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->dialog_button_panel,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtManageChild(instance->about_form);
    XtManageChild(instance->dialog_button_panel);
    XtVaGetValues(instance->about_shellform,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    /*
     * Turn off traversal for invisible sash in dialog's PanedWindow
     */
    dtb_remove_sash_focus(instance->about_panedwin);
    
    /*
     * Add User and Connection callbacks
     */
    	XtAddCallback(instance->about_ok,
		XmNactivateCallback, main_about_ok_CB1,
    		(XtPointer)&(*instance));
return 0;
}



static int 
dtb_main_mainwindow_create(
    DtbMainMainwindowInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Display	*display= (parent == NULL? NULL:XtDisplay(parent));
    
    if (instance->mainwindow == NULL) {
        instance->mainwindow =
            XtVaCreatePopupShell("mainwindow",
                topLevelShellWidgetClass,
                parent,
                XmNallowShellResize, True,
                XmNtitle, "Morsetutor",
                XmNinitialState, NormalState,
                XmNbackground, dtb_cvt_string_to_pixel(parent, "white"),
                NULL);
    }
    if (instance->mainwindow == NULL)
        return -1;

    if (instance->mainwindow_mainwin == NULL) {
        instance->mainwindow_mainwin =
            XtVaCreateWidget("dtb_main_mainwindow_mainwin",
                xmMainWindowWidgetClass,
                instance->mainwindow,
                XmNcommandWindowLocation, XmCOMMAND_ABOVE_WORKSPACE,
                XmNbackground, dtb_cvt_string_to_pixel(instance->mainwindow, "white"),
                NULL);
    }
    if (instance->mainwindow_mainwin == NULL)
        return -1;

    if (instance->mainwindow_form == NULL) {
        instance->mainwindow_form =
            XtVaCreateWidget("mainwindow_form",
                xmFormWidgetClass,
                instance->mainwindow_mainwin,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNresizePolicy, XmRESIZE_GROW,
                XmNheight, 380,
                XmNwidth, 662,
                XmNbackground, dtb_cvt_string_to_pixel(instance->mainwindow_mainwin, "white"),
                NULL);
    }
    if (instance->mainwindow_form == NULL)
        return -1;

    return 0;
}



static int 
dtb_main_about_create(
    DtbMainAboutInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Display	*display= (parent == NULL? NULL:XtDisplay(parent));
    Arg	args[8];	/* need 3 args (add 5 to be safe) */
    int	n = 0;
    
    if (instance->about == NULL) {
        n = 0;
        XtSetArg(args[n], XmNallowShellResize, True);  ++n;
        XtSetArg(args[n], XmNtitle, "About");  ++n;
        XtSetArg(args[n], XmNbackground, dtb_cvt_string_to_pixel(parent, "white"));  ++n;
        instance->about =
            XmCreateDialogShell(parent,
                "dtb_main_about", args, n);
    }
    if (instance->about == NULL)
        return -1;

    if (instance->about_shellform == NULL) {
        instance->about_shellform =
            XtVaCreateWidget("dtb_main_about_shellform",
                xmFormWidgetClass,
                instance->about,
                XmNnoResize, True,
                XmNdefaultPosition, False,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNbackground, dtb_cvt_string_to_pixel(instance->about, "white"),
                NULL);
    }
    if (instance->about_shellform == NULL)
        return -1;

    if (instance->about_panedwin == NULL) {
        instance->about_panedwin =
            XtVaCreateWidget("about_panedwin",
                xmPanedWindowWidgetClass,
                instance->about_shellform,
                XmNbottomOffset, 0,
                XmNbottomPosition, 100,
                XmNbottomAttachment, XmATTACH_POSITION,
                XmNrightOffset, 0,
                XmNrightPosition, 100,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 0,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 0,
                XmNtopPosition, 0,
                XmNtopAttachment, XmATTACH_POSITION,
                XmNsashWidth, 1,
                XmNsashHeight, 1,
                XmNspacing, 0,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNbackground, dtb_cvt_string_to_pixel(instance->about_shellform, "white"),
                NULL);
    }
    if (instance->about_panedwin == NULL)
        return -1;

    if (instance->about_form == NULL) {
        instance->about_form =
            XtVaCreateWidget("about_form",
                xmFormWidgetClass,
                instance->about_panedwin,
                XmNallowResize, True,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNresizePolicy, XmRESIZE_ANY,
                XmNbackground, dtb_cvt_string_to_pixel(instance->about_panedwin, "white"),
                NULL);
    }
    if (instance->about_form == NULL)
        return -1;

    return 0;
}



static int 
dtb_main_menubar_create(
    DtbMainMainwindowInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Arg	args[7];	/* need 2 args (add 5 to be safe) */
    int	n = 0;
    static String	menubar_names[] =
    {
        "File_item", "Edit_item", "Training_item", "Help_item"
    };
    static String	menubar_strings[] =
    {
        "File", "Edit", "Training", "Help"
    };
    int	i = 0;
    static String	menubar_mnemonics[] =
    {
        "F", "E", "T", "H"
    };
    Widget	menubar_items[4];
    
    if (instance->menubar == NULL) {
        n = 0;
        XtSetArg(args[n], XmNrowColumnType, XmMENU_BAR);  ++n;
        instance->menubar =
            XmCreateMenuBar(parent,
                "menubar", args, n);
    }
    if (instance->menubar == NULL)
        return -1;

    for (i = 0; i < XtNumber(menubar_strings); i++)
    {
        label_xmstring = XmStringCreateLocalized(menubar_strings[i]);
        menubar_items[i] = XtVaCreateWidget(menubar_names[i],
            xmCascadeButtonWidgetClass,
            instance->menubar,
            XmNmnemonic, menubar_mnemonics[i]? (KeySym)XStringToKeysym(menubar_mnemonics[i]) : (KeySym)NULL,
            XmNlabelString, label_xmstring,
            NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    instance->menubar_items.File_item = menubar_items[0];
    instance->menubar_items.Edit_item = menubar_items[1];
    instance->menubar_items.Training_item = menubar_items[2];
    instance->menubar_items.Help_item = menubar_items[3];
    return 0;
}



static int 
dtb_main_mainwindow_toolbar_create(
    DtbMainMainwindowInfo instance,
    Widget parent
)
{
    
    if (instance->mainwindow_toolbar == NULL) {
        instance->mainwindow_toolbar =
            XtVaCreateWidget("mainwindow_toolbar",
                xmFormWidgetClass,
                parent,
                XmNresizePolicy, XmRESIZE_GROW,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNheight, 48,
                NULL);
    }
    if (instance->mainwindow_toolbar == NULL)
        return -1;

    return 0;
}



static int 
dtb_main_menubar_file_item_file_menu_create(
    DtbMainMainwindowInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Arg	args[6];	/* need 1 args (add 5 to be safe) */
    int	n = 0;
    
    if (instance->menubar_File_item_File_menu == NULL) {
        n = 0;
        XtSetArg(args[n], XmNtearOffModel, XmTEAR_OFF_DISABLED);  ++n;
        instance->menubar_File_item_File_menu =
            XmCreatePulldownMenu(parent,
                "menubar_File_item_File_menu", args, n);
    }
    if (instance->menubar_File_item_File_menu == NULL)
        return -1;

    label_xmstring = XmStringCreateLocalized("Connect...");
    if (instance->menubar_File_item_File_menu_items.items_item == NULL) {
        instance->menubar_File_item_File_menu_items.items_item =
            XtVaCreateManagedWidget("items_item",
                xmPushButtonWidgetClass,
                instance->menubar_File_item_File_menu,
                XmNmnemonic, XStringToKeysym("C"),
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->menubar_File_item_File_menu_items.items_item == NULL)
        return -1;

    if (instance->menubar_File_item_File_menu_items.separator1_item == NULL) {
        instance->menubar_File_item_File_menu_items.separator1_item =
            XtVaCreateManagedWidget("separator1_item",
                xmSeparatorWidgetClass,
                instance->menubar_File_item_File_menu,
                XmNseparatorType, XmSHADOW_ETCHED_OUT,
                NULL);
    }
    if (instance->menubar_File_item_File_menu_items.separator1_item == NULL)
        return -1;

    label_xmstring = XmStringCreateLocalized("Quit");
    if (instance->menubar_File_item_File_menu_items.Quit_item == NULL) {
        instance->menubar_File_item_File_menu_items.Quit_item =
            XtVaCreateManagedWidget("Quit_item",
                xmPushButtonWidgetClass,
                instance->menubar_File_item_File_menu,
                XmNmnemonic, XStringToKeysym("Q"),
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->menubar_File_item_File_menu_items.Quit_item == NULL)
        return -1;

    return 0;
}



static int 
dtb_main_menubar_edit_item_edit_menu_create(
    DtbMainMainwindowInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Arg	args[6];	/* need 1 args (add 5 to be safe) */
    int	n = 0;
    static String	menubar_Edit_item_Edit_menu_names[] =
    {
        "items_item", "items_item2", "items_item3"
    };
    static String	menubar_Edit_item_Edit_menu_strings[] =
    {
        "Speed settings...", "Character set...", "Morse code..."
    };
    int	i = 0;
    static String	menubar_Edit_item_Edit_menu_mnemonics[] =
    {
        "S", "C", "M"
    };
    Widget	menubar_Edit_item_Edit_menu_items[3];
    
    if (instance->menubar_Edit_item_Edit_menu == NULL) {
        n = 0;
        XtSetArg(args[n], XmNtearOffModel, XmTEAR_OFF_DISABLED);  ++n;
        instance->menubar_Edit_item_Edit_menu =
            XmCreatePulldownMenu(parent,
                "menubar_Edit_item_Edit_menu", args, n);
    }
    if (instance->menubar_Edit_item_Edit_menu == NULL)
        return -1;

    for (i = 0; i < XtNumber(menubar_Edit_item_Edit_menu_strings); i++)
    {
        label_xmstring = XmStringCreateLocalized(menubar_Edit_item_Edit_menu_strings[i]);
        menubar_Edit_item_Edit_menu_items[i] = XtVaCreateWidget(menubar_Edit_item_Edit_menu_names[i],
            xmPushButtonWidgetClass,
            instance->menubar_Edit_item_Edit_menu,
            XmNmnemonic, menubar_Edit_item_Edit_menu_mnemonics[i]? (KeySym)XStringToKeysym(menubar_Edit_item_Edit_menu_mnemonics[i]) : (KeySym)NULL,
            XmNlabelString, label_xmstring,
            NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    instance->menubar_Edit_item_Edit_menu_items.items_item = menubar_Edit_item_Edit_menu_items[0];
    instance->menubar_Edit_item_Edit_menu_items.items_item2 = menubar_Edit_item_Edit_menu_items[1];
    instance->menubar_Edit_item_Edit_menu_items.items_item3 = menubar_Edit_item_Edit_menu_items[2];
    return 0;
}



static int 
dtb_main_menubar_training_item_training_menu_create(
    DtbMainMainwindowInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Arg	args[6];	/* need 1 args (add 5 to be safe) */
    int	n = 0;
    static String	menubar_Training_item_Training_menu_names[] =
    {
        "Start_item"
    };
    static String	menubar_Training_item_Training_menu_strings[] =
    {
        "Start"
    };
    int	i = 0;
    static String	menubar_Training_item_Training_menu_mnemonics[] =
    {
        "S"
    };
    Widget	menubar_Training_item_Training_menu_items[1];
    
    if (instance->menubar_Training_item_Training_menu == NULL) {
        n = 0;
        XtSetArg(args[n], XmNtearOffModel, XmTEAR_OFF_DISABLED);  ++n;
        instance->menubar_Training_item_Training_menu =
            XmCreatePulldownMenu(parent,
                "menubar_Training_item_Training_menu", args, n);
    }
    if (instance->menubar_Training_item_Training_menu == NULL)
        return -1;

    for (i = 0; i < XtNumber(menubar_Training_item_Training_menu_strings); i++)
    {
        label_xmstring = XmStringCreateLocalized(menubar_Training_item_Training_menu_strings[i]);
        menubar_Training_item_Training_menu_items[i] = XtVaCreateWidget(menubar_Training_item_Training_menu_names[i],
            xmPushButtonWidgetClass,
            instance->menubar_Training_item_Training_menu,
            XmNmnemonic, menubar_Training_item_Training_menu_mnemonics[i]? (KeySym)XStringToKeysym(menubar_Training_item_Training_menu_mnemonics[i]) : (KeySym)NULL,
            XmNlabelString, label_xmstring,
            NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    instance->menubar_Training_item_Training_menu_items.Start_item = menubar_Training_item_Training_menu_items[0];
    return 0;
}



static int 
dtb_main_menubar_help_item_help_menu_create(
    DtbMainMainwindowInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Arg	args[6];	/* need 1 args (add 5 to be safe) */
    int	n = 0;
    static String	menubar_Help_item_Help_menu_names[] =
    {
        "items_item"
    };
    static String	menubar_Help_item_Help_menu_strings[] =
    {
        "About..."
    };
    int	i = 0;
    static String	menubar_Help_item_Help_menu_mnemonics[] =
    {
        "A"
    };
    Widget	menubar_Help_item_Help_menu_items[1];
    
    if (instance->menubar_Help_item_Help_menu == NULL) {
        n = 0;
        XtSetArg(args[n], XmNtearOffModel, XmTEAR_OFF_DISABLED);  ++n;
        instance->menubar_Help_item_Help_menu =
            XmCreatePulldownMenu(parent,
                "menubar_Help_item_Help_menu", args, n);
    }
    if (instance->menubar_Help_item_Help_menu == NULL)
        return -1;

    for (i = 0; i < XtNumber(menubar_Help_item_Help_menu_strings); i++)
    {
        label_xmstring = XmStringCreateLocalized(menubar_Help_item_Help_menu_strings[i]);
        menubar_Help_item_Help_menu_items[i] = XtVaCreateWidget(menubar_Help_item_Help_menu_names[i],
            xmPushButtonWidgetClass,
            instance->menubar_Help_item_Help_menu,
            XmNmnemonic, menubar_Help_item_Help_menu_mnemonics[i]? (KeySym)XStringToKeysym(menubar_Help_item_Help_menu_mnemonics[i]) : (KeySym)NULL,
            XmNlabelString, label_xmstring,
            NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    instance->menubar_Help_item_Help_menu_items.items_item = menubar_Help_item_Help_menu_items[0];
    return 0;
}



static int 
dtb_main_connect_button_create(
    DtbMainMainwindowInfo instance,
    Widget parent
)
{
    int	return_code = 0;
    Display *	display = NULL;
    Pixmap	label_pixmap = NULL;
    Drawable	drawable = NULL;
    
    display = XtDisplay(parent);
    drawable = DefaultRootWindow(display);
    
    if (instance->connectButton == NULL) {
        instance->connectButton =
            XtVaCreateWidget("connectButton",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightAttachment, XmATTACH_NONE,
                XmNleftOffset, 5,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 4,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, True,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNy, 4,
                XmNx, 5,
                NULL);
        dtb_set_label_from_image_file(instance->connectButton, "connect.m");
    }
    if (instance->connectButton == NULL)
        return -1;

    return 0;
}



static int 
dtb_main_start_button_create(
    DtbMainMainwindowInfo instance,
    Widget parent
)
{
    int	return_code = 0;
    Display *	display = NULL;
    Pixmap	label_pixmap = NULL;
    Drawable	drawable = NULL;
    
    display = XtDisplay(parent);
    drawable = DefaultRootWindow(display);
    
    if (instance->startButton == NULL) {
        instance->startButton =
            XtVaCreateWidget("startButton",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightAttachment, XmATTACH_NONE,
                XmNleftOffset, 12,
                XmNleftAttachment, XmATTACH_WIDGET,
                XmNtopOffset, 4,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, True,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNy, 4,
                XmNx, 57,
                NULL);
        dtb_set_label_from_image_file(instance->startButton, "key_start.m");
    }
    if (instance->startButton == NULL)
        return -1;

    return 0;
}



static int 
dtb_main_pause_button_create(
    DtbMainMainwindowInfo instance,
    Widget parent
)
{
    int	return_code = 0;
    Display *	display = NULL;
    Pixmap	label_pixmap = NULL;
    Drawable	drawable = NULL;
    
    display = XtDisplay(parent);
    drawable = DefaultRootWindow(display);
    
    if (instance->pauseButton == NULL) {
        instance->pauseButton =
            XtVaCreateWidget("pauseButton",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightAttachment, XmATTACH_NONE,
                XmNleftOffset, 5,
                XmNleftAttachment, XmATTACH_WIDGET,
                XmNtopOffset, 4,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, True,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNy, 4,
                XmNx, 103,
                NULL);
        dtb_set_label_from_image_file(instance->pauseButton, "key_pause.m");
    }
    if (instance->pauseButton == NULL)
        return -1;

    return 0;
}



static int 
dtb_main_stop_button_create(
    DtbMainMainwindowInfo instance,
    Widget parent
)
{
    int	return_code = 0;
    Display *	display = NULL;
    Pixmap	label_pixmap = NULL;
    Drawable	drawable = NULL;
    
    display = XtDisplay(parent);
    drawable = DefaultRootWindow(display);
    
    if (instance->stopButton == NULL) {
        instance->stopButton =
            XtVaCreateWidget("stopButton",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightAttachment, XmATTACH_NONE,
                XmNleftOffset, 5,
                XmNleftAttachment, XmATTACH_WIDGET,
                XmNtopOffset, 4,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, True,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNy, 6,
                XmNx, 149,
                NULL);
        dtb_set_label_from_image_file(instance->stopButton, "key_stop.m");
    }
    if (instance->stopButton == NULL)
        return -1;

    return 0;
}



static int 
dtb_main_sounder_button_create(
    DtbMainMainwindowInfo instance,
    Widget parent
)
{
    int	return_code = 0;
    Display *	display = NULL;
    Pixmap	label_pixmap = NULL;
    Drawable	drawable = NULL;
    
    display = XtDisplay(parent);
    drawable = DefaultRootWindow(display);
    
    if (instance->sounderButton == NULL) {
        instance->sounderButton =
            XtVaCreateWidget("sounderButton",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightAttachment, XmATTACH_NONE,
                XmNleftOffset, 12,
                XmNleftAttachment, XmATTACH_WIDGET,
                XmNtopOffset, 4,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, True,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNy, 7,
                XmNx, 203,
                NULL);
        dtb_set_label_from_image_file(instance->sounderButton, "sounder.m");
    }
    if (instance->sounderButton == NULL)
        return -1;

    return 0;
}



static int 
dtb_main_send_button_create(
    DtbMainMainwindowInfo instance,
    Widget parent
)
{
    int	return_code = 0;
    Display *	display = NULL;
    Pixmap	label_pixmap = NULL;
    Drawable	drawable = NULL;
    
    display = XtDisplay(parent);
    drawable = DefaultRootWindow(display);
    
    if (instance->sendButton == NULL) {
        instance->sendButton =
            XtVaCreateWidget("sendButton",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightAttachment, XmATTACH_NONE,
                XmNleftOffset, 5,
                XmNleftAttachment, XmATTACH_WIDGET,
                XmNtopOffset, 4,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, True,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNy, 12,
                XmNx, 250,
                NULL);
        dtb_set_label_from_image_file(instance->sendButton, "send.m");
    }
    if (instance->sendButton == NULL)
        return -1;

    return 0;
}



static int 
dtb_main_rx_box_create(
    DtbMainMainwindowInfo instance,
    Widget parent
)
{
    Arg	args[20];	/* need 15 args (add 5 to be safe) */
    int	n = 0;
    
    if (instance->rxBox == NULL) {
        n = 0;
        XtSetArg(args[n], XmNbottomOffset, 0);  ++n;
        XtSetArg(args[n], XmNbottomAttachment, XmATTACH_FORM);  ++n;
        XtSetArg(args[n], XmNrightOffset, 0);  ++n;
        XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM);  ++n;
        XtSetArg(args[n], XmNleftOffset, 0);  ++n;
        XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM);  ++n;
        XtSetArg(args[n], XmNtopAttachment, XmATTACH_NONE);  ++n;
        XtSetArg(args[n], XmNwordWrap, True);  ++n;
        XtSetArg(args[n], XmNeditMode, XmMULTI_LINE_EDIT);  ++n;
        XtSetArg(args[n], XmNcolumns, 48);  ++n;
        XtSetArg(args[n], XmNrows, 1);  ++n;
        XtSetArg(args[n], XmNcursorPositionVisible, True);  ++n;
        XtSetArg(args[n], XmNeditable, True);  ++n;
        XtSetArg(args[n], XmNy, 135);  ++n;
        XtSetArg(args[n], XmNx, 0);  ++n;
        instance->rxBox =
            XmCreateText(parent,
                "rxBox", args, n);
    }
    if (instance->rxBox == NULL)
        return -1;

    return 0;
}



static int 
dtb_main_output_box_create(
    DtbMainMainwindowInfo instance,
    Widget parent
)
{
    Arg	args[28];	/* need 23 args (add 5 to be safe) */
    int	n = 0;
    
    if (instance->outputBox == NULL) {
        n = 0;
        XtSetArg(args[n], XmNbottomOffset, 2);  ++n;
        XtSetArg(args[n], XmNbottomAttachment, XmATTACH_WIDGET);  ++n;
        XtSetArg(args[n], XmNrightOffset, 0);  ++n;
        XtSetArg(args[n], XmNrightAttachment, XmATTACH_FORM);  ++n;
        XtSetArg(args[n], XmNleftOffset, 0);  ++n;
        XtSetArg(args[n], XmNleftAttachment, XmATTACH_FORM);  ++n;
        XtSetArg(args[n], XmNtopOffset, 0);  ++n;
        XtSetArg(args[n], XmNtopAttachment, XmATTACH_FORM);  ++n;
        XtSetArg(args[n], XmNscrollBarDisplayPolicy, XmAUTOMATIC);  ++n;
        XtSetArg(args[n], XmNvisualPolicy, XmVARIABLE);  ++n;
        XtSetArg(args[n], XmNscrollingPolicy, XmAPPLICATION_DEFINED);  ++n;
        XtSetArg(args[n], XmNheight, 348);  ++n;
        XtSetArg(args[n], XmNwidth, 662);  ++n;
        XtSetArg(args[n], XmNy, 16);  ++n;
        XtSetArg(args[n], XmNx, 37);  ++n;
        XtSetArg(args[n], XmNwordWrap, True);  ++n;
        XtSetArg(args[n], XmNeditMode, XmMULTI_LINE_EDIT);  ++n;
        XtSetArg(args[n], XmNscrollHorizontal, False);  ++n;
        XtSetArg(args[n], XmNscrollVertical, True);  ++n;
        XtSetArg(args[n], XmNcolumns, 8);  ++n;
        XtSetArg(args[n], XmNrows, 4);  ++n;
        XtSetArg(args[n], XmNcursorPositionVisible, False);  ++n;
        XtSetArg(args[n], XmNeditable, False);  ++n;
        instance->outputBox =
            XmCreateScrolledText(parent,
                "outputBox", args, n);
    }
    instance->outputBox_scrolledwin = XtParent(instance->outputBox);
    return 0;
}



static int 
dtb_main_dialog_button_panel_create(
    DtbMainAboutInfo instance,
    Widget parent
)
{
    
    if (instance->dialog_button_panel == NULL) {
        instance->dialog_button_panel =
            XtVaCreateWidget("dialog_button_panel",
                xmFormWidgetClass,
                parent,
                XmNpaneMaximum, 48,
                XmNpaneMinimum, 48,
                XmNresizePolicy, XmRESIZE_GROW,
                XmNmarginHeight, 7,
                XmNmarginWidth, 7,
                XmNpositionIndex, 1,
                XmNheight, 48,
                NULL);
    }
    if (instance->dialog_button_panel == NULL)
        return -1;

    return 0;
}



static int 
dtb_main_controlpane_create(
    DtbMainAboutInfo instance,
    Widget parent
)
{
    
    if (instance->controlpane == NULL) {
        instance->controlpane =
            XtVaCreateWidget("controlpane",
                xmFormWidgetClass,
                parent,
                XmNbottomOffset, 0,
                XmNbottomAttachment, XmATTACH_FORM,
                XmNrightOffset, 0,
                XmNrightAttachment, XmATTACH_FORM,
                XmNleftOffset, 0,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 0,
                XmNtopAttachment, XmATTACH_FORM,
                XmNresizePolicy, XmRESIZE_GROW,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNheight, 304,
                XmNwidth, 454,
                XmNy, 31,
                XmNx, 120,
                NULL);
    }
    if (instance->controlpane == NULL)
        return -1;

    return 0;
}



static int 
dtb_main_label_create(
    DtbMainAboutInfo instance,
    Widget parent
)
{
    int	return_code = 0;
    Display *	display = NULL;
    Pixmap	label_pixmap = NULL;
    Drawable	drawable = NULL;
    
    display = XtDisplay(parent);
    drawable = DefaultRootWindow(display);
    
    if (instance->label == NULL) {
        instance->label =
            XtVaCreateWidget("label",
                xmLabelWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightAttachment, XmATTACH_NONE,
                XmNleftOffset, 0,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 0,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, True,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNy, 16,
                XmNx, 19,
                NULL);
        dtb_set_label_from_image_file(instance->label, "about");
    }
    if (instance->label == NULL)
        return -1;

    return 0;
}



static int 
dtb_main_about_ok_create(
    DtbMainAboutInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized("OK");
    if (instance->about_ok == NULL) {
        instance->about_ok =
            XtVaCreateWidget("about_ok",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 0,
                XmNrightPosition, 60,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 40,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, True,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNdefaultButtonShadowThickness, 1,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->about_ok == NULL)
        return -1;

    return 0;
}

