/*** DTB_USER_CODE_START vvv Add file header below vvv ***/
/*** DTB_USER_CODE_END   ^^^ Add file header above ^^^ ***/

/*
 * File: settings_stubs.c
 * Contains: Module callbacks and connection functions
 *
 * This file was generated by dtcodegen, from module settings
 *
 * Any text may be added between the DTB_USER_CODE_START and
 * DTB_USER_CODE_END comments (even non-C code). Descriptive comments
 * are provided only as an aid.
 *
 *  ** EDIT ONLY WITHIN SECTIONS MARKED WITH DTB_USER_CODE COMMENTS.  **
 *  ** ALL OTHER MODIFICATIONS WILL BE OVERWRITTEN. DO NOT MODIFY OR  **
 *  ** DELETE THE GENERATED COMMENTS!                                 **
 */

#include <stdio.h>
#include <Xm/Xm.h>
#include "dtb_utils.h"
#include "settings_ui.h"

/*
 * Header files for cross-module connections
 */
#include "main_ui.h"


/**************************************************************************
 *** DTB_USER_CODE_START
 ***
 *** All necessary header files have been included.
 ***
 *** Add include files, types, macros, externs, and user functions here.
 ***/
#include "configuration.h"

/*** DTB_USER_CODE_END
 ***
 *** End of user code section
 ***
 **************************************************************************/



void 
settings_speed_cancel_CB1(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    DtbSettingsSpeedDialogInfo	dtbTarget = (DtbSettingsSpeedDialogInfo)clientData;
    DtbSettingsSpeedDialogInfo	instance = dtbTarget;	/* obsolete */
    
    if (!(dtbTarget->initialized))
    {
        dtb_settings_speed_dialog_initialize(dtbTarget, dtb_main_mainwindow.mainwindow);
    }
    XtUnmanageChild(instance->speedDialog_shellform);
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
settings_speed_ok_CB1(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    DtbSettingsSpeedDialogInfo	dtbTarget = (DtbSettingsSpeedDialogInfo)clientData;
    DtbSettingsSpeedDialogInfo	instance = dtbTarget;	/* obsolete */
    
    if (!(dtbTarget->initialized))
    {
        dtb_settings_speed_dialog_initialize(dtbTarget, dtb_main_mainwindow.mainwindow);
    }
    XtUnmanageChild(instance->speedDialog_shellform);
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
settings_code_ok_CB1(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    DtbSettingsCodeDialogInfo	dtbTarget = (DtbSettingsCodeDialogInfo)clientData;
    DtbSettingsCodeDialogInfo	instance = dtbTarget;	/* obsolete */
    
    if (!(dtbTarget->initialized))
    {
        dtb_settings_code_dialog_initialize(dtbTarget, dtb_main_mainwindow.mainwindow);
    }
    XtUnmanageChild(instance->codeDialog_shellform);
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
settings_code_cancel_CB1(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    DtbSettingsCodeDialogInfo	dtbTarget = (DtbSettingsCodeDialogInfo)clientData;
    DtbSettingsCodeDialogInfo	instance = dtbTarget;	/* obsolete */
    
    if (!(dtbTarget->initialized))
    {
        dtb_settings_code_dialog_initialize(dtbTarget, dtb_main_mainwindow.mainwindow);
    }
    XtUnmanageChild(instance->codeDialog_shellform);
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
setSpeed(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
	Arg args[3];
	int value;
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
	XtSetArg(args[0], XmNvalue, &value);

	XtGetValues(dtb_settings_speed_dialog.Speed, args, 1);
	vConfiguration.speed = value;
	XtGetValues(dtb_settings_speed_dialog.farnsworth, args, 1);
	vConfiguration.farnsworth = value;
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
setCode(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
	Arg args[3];
	int value;
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
	XtSetArg(args[0], XmNset, &value);

	XtGetValues(dtb_settings_code_dialog.codeBox_items.American_item, args, 1);
	if (value & 0x01) {
		vConfiguration.code = CODE_AMERICAN;
	}

	XtGetValues(dtb_settings_code_dialog.codeBox_items.Continental_item, args, 1);
	if (value & 0x01) {
		vConfiguration.code = CODE_CONTINENTAL;
	}
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
initSpeedDialog(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
	XtVaSetValues(dtb_settings_speed_dialog.Speed, XmNvalue, vConfiguration.speed, NULL);
	XtVaSetValues(dtb_settings_speed_dialog.farnsworth, XmNvalue, vConfiguration.farnsworth, NULL);
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}


void 
initCodeDialog(
    Widget widget,
    XtPointer clientData,
    XtPointer callData
)
{
    /*** DTB_USER_CODE_START vvv Add C variables and code below vvv ***/
    /*** DTB_USER_CODE_END   ^^^ Add C variables and code above ^^^ ***/
    
    /*** DTB_USER_CODE_START vvv Add C code below vvv ***/
	switch (vConfiguration.code) {
		case CODE_AMERICAN:
			XtVaSetValues(dtb_settings_code_dialog.codeBox_items.American_item, XmNset, 1, NULL);
			XtVaSetValues(dtb_settings_code_dialog.codeBox_items.Continental_item, XmNset, 0, NULL);
			break;
		case CODE_CONTINENTAL:
			XtVaSetValues(dtb_settings_code_dialog.codeBox_items.American_item, XmNset, 0, NULL);
			XtVaSetValues(dtb_settings_code_dialog.codeBox_items.Continental_item, XmNset, 1, NULL);
			break;
	}
    /*** DTB_USER_CODE_END   ^^^ Add C code above ^^^ ***/
}



/**************************************************************************
 *** DTB_USER_CODE_START
 ***
 *** All automatically-generated data and functions have been defined.
 ***
 *** Add new functions here, or at the top of the file.
 ***/

/*** DTB_USER_CODE_END
 ***
 *** End of user code section
 ***
 **************************************************************************/


