/*
 * File: settings_ui.c
 * Contains: user module object initialize and create functions
 *
 * This file was generated by dtcodegen, from module settings
 *
 *    ** DO NOT MODIFY BY HAND - ALL MODIFICATIONS WILL BE LOST **
 */


#include <stdlib.h>
#include <X11/Intrinsic.h>
#include <Xm/DialogS.h>
#include <Xm/Form.h>
#include <Xm/PanedW.h>
#include <Xm/RowColumn.h>
#include <Xm/Separator.h>
#include <Xm/Label.h>
#include <Xm/Scale.h>
#include <Xm/PushB.h>
#include <Xm/ToggleB.h>
#include "dtb_utils.h"
#include "morsetutor.h"
#include "settings_ui.h"


DtbSettingsSpeedDialogInfoRec	dtb_settings_speed_dialog = 
{
    False	 /* initialized */
};

DtbSettingsCodeDialogInfoRec	dtb_settings_code_dialog = 
{
    False	 /* initialized */
};

/*
 * Widget create procedure decls
 */
static int dtb_settings_speed_dialog_create(
    DtbSettingsSpeedDialogInfo	instance,
    Widget	parent
);
static int dtb_settings_code_dialog_create(
    DtbSettingsCodeDialogInfo	instance,
    Widget	parent
);
static int dtb_settings_dialog_button_panel_create(
    DtbSettingsSpeedDialogInfo	instance,
    Widget	parent
);
static int dtb_settings_controlpane_create(
    DtbSettingsSpeedDialogInfo	instance,
    Widget	parent
);
static int dtb_settings_speed_create(
    DtbSettingsSpeedDialogInfo	instance,
    Widget	parent
);
static int dtb_settings_farnsworth_create(
    DtbSettingsSpeedDialogInfo	instance,
    Widget	parent
);
static int dtb_settings_separator2_create(
    DtbSettingsSpeedDialogInfo	instance,
    Widget	parent
);
static int dtb_settings_speed_ok_create(
    DtbSettingsSpeedDialogInfo	instance,
    Widget	parent
);
static int dtb_settings_speed_cancel_create(
    DtbSettingsSpeedDialogInfo	instance,
    Widget	parent
);
static int dtb_settings_dialog_button_panel2_create(
    DtbSettingsCodeDialogInfo	instance,
    Widget	parent
);
static int dtb_settings_controlpane2_create(
    DtbSettingsCodeDialogInfo	instance,
    Widget	parent
);
static int dtb_settings_code_box_create(
    DtbSettingsCodeDialogInfo	instance,
    Widget	parent
);
static int dtb_settings_separator_create(
    DtbSettingsCodeDialogInfo	instance,
    Widget	parent
);
static int dtb_settings_code_ok_create(
    DtbSettingsCodeDialogInfo	instance,
    Widget	parent
);
static int dtb_settings_code_cancel_create(
    DtbSettingsCodeDialogInfo	instance,
    Widget	parent
);

int 
dtbSettingsSpeedDialogInfo_clear(DtbSettingsSpeedDialogInfo instance)
{
    memset((void *)(instance), 0, sizeof(*instance));
    return 0;
}

int 
dtb_settings_speed_dialog_initialize(
    DtbSettingsSpeedDialogInfo instance,
    Widget parent
)
{
    WidgetList	children = NULL;
    int		numChildren = 0;
    if (instance->initialized)
    {
        return 0;
    }
    instance->initialized = True;

    dtb_settings_speed_dialog_create(instance,
        parent);
    dtb_settings_dialog_button_panel_create(instance,
        instance->speedDialog_panedwin);
    dtb_settings_controlpane_create(instance,
        instance->speedDialog_form);
    dtb_settings_speed_create(instance,
        instance->controlpane);
    dtb_settings_farnsworth_create(instance,
        instance->controlpane);
    dtb_settings_separator2_create(instance,
        instance->controlpane);
    dtb_settings_speed_ok_create(instance,
        instance->dialog_button_panel);
    dtb_settings_speed_cancel_create(instance,
        instance->dialog_button_panel);
    
    /*
     * Add widget-reference resources.
     */
    
    XtVaSetValues(instance->speedDialog_shellform,
        XmNdefaultButton, instance->speed_ok,
        NULL);
    
    XtVaSetValues(instance->farnsworth_rowcolumn,
        XmNtopWidget, instance->Speed_rowcolumn,
        NULL);
    
    /*
     * Call utility functions to do group layout
     */
    
    /*
     * Make Dialog Button-Panel & Footer a fixed height
     */
    {
        Dimension	pane_height;

        XtVaGetValues(instance->dialog_button_panel,
            XmNheight, &pane_height,
            NULL);
        XtVaSetValues(instance->dialog_button_panel,
            XmNpaneMinimum,   pane_height,
            XmNpaneMaximum,   pane_height,
            NULL);

    }
    
    /*
     * Manage the tree, from the bottom up.
     */
    XtVaGetValues(instance->Speed_rowcolumn,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->farnsworth_rowcolumn,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->controlpane,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->speedDialog_form,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->dialog_button_panel,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtManageChild(instance->speedDialog_form);
    XtManageChild(instance->dialog_button_panel);
    XtVaGetValues(instance->speedDialog_shellform,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    /*
     * Turn off traversal for invisible sash in dialog's PanedWindow
     */
    dtb_remove_sash_focus(instance->speedDialog_panedwin);
    
    /*
     * Add User and Connection callbacks
     */
    	XtAddCallback(instance->speedDialog,
		XmNpopupCallback, initSpeedDialog,
    		(XtPointer)&(*instance));
	XtAddCallback(instance->speed_ok,
		XmNactivateCallback, settings_speed_ok_CB1,
		(XtPointer)&(*instance));
	XtAddCallback(instance->speed_ok,
		XmNactivateCallback, setSpeed,
		(XtPointer)&(*instance));
	XtAddCallback(instance->speed_cancel,
		XmNactivateCallback, settings_speed_cancel_CB1,
		(XtPointer)&(*instance));
return 0;
}

int 
dtbSettingsCodeDialogInfo_clear(DtbSettingsCodeDialogInfo instance)
{
    memset((void *)(instance), 0, sizeof(*instance));
    return 0;
}

int 
dtb_settings_code_dialog_initialize(
    DtbSettingsCodeDialogInfo instance,
    Widget parent
)
{
    WidgetList	children = NULL;
    int		numChildren = 0;
    if (instance->initialized)
    {
        return 0;
    }
    instance->initialized = True;

    dtb_settings_code_dialog_create(instance,
        parent);
    dtb_settings_dialog_button_panel2_create(instance,
        instance->codeDialog_panedwin);
    dtb_settings_controlpane2_create(instance,
        instance->codeDialog_form);
    dtb_settings_code_box_create(instance,
        instance->controlpane2);
    dtb_settings_separator_create(instance,
        instance->controlpane2);
    dtb_settings_code_ok_create(instance,
        instance->dialog_button_panel2);
    dtb_settings_code_cancel_create(instance,
        instance->dialog_button_panel2);
    
    /*
     * Add widget-reference resources.
     */
    
    XtVaSetValues(instance->codeDialog_shellform,
        XmNdefaultButton, instance->code_ok,
        NULL);
    
    /*
     * Call utility functions to do group layout
     */
    
    /*
     * Make Dialog Button-Panel & Footer a fixed height
     */
    {
        Dimension	pane_height;

        XtVaGetValues(instance->dialog_button_panel2,
            XmNheight, &pane_height,
            NULL);
        XtVaSetValues(instance->dialog_button_panel2,
            XmNpaneMinimum,   pane_height,
            XmNpaneMaximum,   pane_height,
            NULL);

    }
    
    /*
     * Manage the tree, from the bottom up.
     */
    XtVaGetValues(instance->codeBox,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->codeBox_rowcolumn,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->controlpane2,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->codeDialog_form,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtVaGetValues(instance->dialog_button_panel2,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    XtManageChild(instance->codeDialog_form);
    XtManageChild(instance->dialog_button_panel2);
    XtVaGetValues(instance->codeDialog_shellform,
        XmNchildren, &children, XmNnumChildren, &numChildren, NULL);
    XtManageChildren(children, numChildren);
    /*
     * Turn off traversal for invisible sash in dialog's PanedWindow
     */
    dtb_remove_sash_focus(instance->codeDialog_panedwin);
    
    /*
     * Add User and Connection callbacks
     */
    	XtAddCallback(instance->codeDialog,
		XmNpopupCallback, initCodeDialog,
    		(XtPointer)&(*instance));
	XtAddCallback(instance->code_ok,
		XmNactivateCallback, settings_code_ok_CB1,
		(XtPointer)&(*instance));
	XtAddCallback(instance->code_ok,
		XmNactivateCallback, setCode,
		(XtPointer)&(*instance));
	XtAddCallback(instance->code_cancel,
		XmNactivateCallback, settings_code_cancel_CB1,
		(XtPointer)&(*instance));
return 0;
}



static int 
dtb_settings_speed_dialog_create(
    DtbSettingsSpeedDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Display	*display= (parent == NULL? NULL:XtDisplay(parent));
    Arg	args[8];	/* need 3 args (add 5 to be safe) */
    int	n = 0;
    
    if (instance->speedDialog == NULL) {
        n = 0;
        XtSetArg(args[n], XmNallowShellResize, True);  ++n;
        XtSetArg(args[n], XmNtitle, "Speed");  ++n;
        XtSetArg(args[n], XmNbackground, dtb_cvt_string_to_pixel(parent, "white"));  ++n;
        instance->speedDialog =
            XmCreateDialogShell(parent,
                "dtb_settings_speedDialog", args, n);
    }
    if (instance->speedDialog == NULL)
        return -1;

    if (instance->speedDialog_shellform == NULL) {
        instance->speedDialog_shellform =
            XtVaCreateWidget("dtb_settings_speedDialog_shellform",
                xmFormWidgetClass,
                instance->speedDialog,
                XmNnoResize, True,
                XmNdefaultPosition, False,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNbackground, dtb_cvt_string_to_pixel(instance->speedDialog, "white"),
                NULL);
    }
    if (instance->speedDialog_shellform == NULL)
        return -1;

    if (instance->speedDialog_panedwin == NULL) {
        instance->speedDialog_panedwin =
            XtVaCreateWidget("speedDialog_panedwin",
                xmPanedWindowWidgetClass,
                instance->speedDialog_shellform,
                XmNbottomOffset, 0,
                XmNbottomPosition, 100,
                XmNbottomAttachment, XmATTACH_POSITION,
                XmNrightOffset, 0,
                XmNrightPosition, 100,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 0,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 0,
                XmNtopPosition, 0,
                XmNtopAttachment, XmATTACH_POSITION,
                XmNsashWidth, 1,
                XmNsashHeight, 1,
                XmNspacing, 0,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNbackground, dtb_cvt_string_to_pixel(instance->speedDialog_shellform, "white"),
                NULL);
    }
    if (instance->speedDialog_panedwin == NULL)
        return -1;

    if (instance->speedDialog_form == NULL) {
        instance->speedDialog_form =
            XtVaCreateWidget("speedDialog_form",
                xmFormWidgetClass,
                instance->speedDialog_panedwin,
                XmNallowResize, True,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNresizePolicy, XmRESIZE_ANY,
                XmNbackground, dtb_cvt_string_to_pixel(instance->speedDialog_panedwin, "white"),
                NULL);
    }
    if (instance->speedDialog_form == NULL)
        return -1;

    return 0;
}



static int 
dtb_settings_code_dialog_create(
    DtbSettingsCodeDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Display	*display= (parent == NULL? NULL:XtDisplay(parent));
    Arg	args[8];	/* need 3 args (add 5 to be safe) */
    int	n = 0;
    
    if (instance->codeDialog == NULL) {
        n = 0;
        XtSetArg(args[n], XmNallowShellResize, True);  ++n;
        XtSetArg(args[n], XmNtitle, "Morse Code");  ++n;
        XtSetArg(args[n], XmNbackground, dtb_cvt_string_to_pixel(parent, "white"));  ++n;
        instance->codeDialog =
            XmCreateDialogShell(parent,
                "dtb_settings_codeDialog", args, n);
    }
    if (instance->codeDialog == NULL)
        return -1;

    if (instance->codeDialog_shellform == NULL) {
        instance->codeDialog_shellform =
            XtVaCreateWidget("dtb_settings_codeDialog_shellform",
                xmFormWidgetClass,
                instance->codeDialog,
                XmNnoResize, True,
                XmNdefaultPosition, False,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNbackground, dtb_cvt_string_to_pixel(instance->codeDialog, "white"),
                NULL);
    }
    if (instance->codeDialog_shellform == NULL)
        return -1;

    if (instance->codeDialog_panedwin == NULL) {
        instance->codeDialog_panedwin =
            XtVaCreateWidget("codeDialog_panedwin",
                xmPanedWindowWidgetClass,
                instance->codeDialog_shellform,
                XmNbottomOffset, 0,
                XmNbottomPosition, 100,
                XmNbottomAttachment, XmATTACH_POSITION,
                XmNrightOffset, 0,
                XmNrightPosition, 100,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 0,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 0,
                XmNtopPosition, 0,
                XmNtopAttachment, XmATTACH_POSITION,
                XmNsashWidth, 1,
                XmNsashHeight, 1,
                XmNspacing, 0,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNbackground, dtb_cvt_string_to_pixel(instance->codeDialog_shellform, "white"),
                NULL);
    }
    if (instance->codeDialog_panedwin == NULL)
        return -1;

    if (instance->codeDialog_form == NULL) {
        instance->codeDialog_form =
            XtVaCreateWidget("codeDialog_form",
                xmFormWidgetClass,
                instance->codeDialog_panedwin,
                XmNallowResize, True,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNresizePolicy, XmRESIZE_GROW,
                XmNheight, 124,
                XmNwidth, 334,
                XmNbackground, dtb_cvt_string_to_pixel(instance->codeDialog_panedwin, "white"),
                NULL);
    }
    if (instance->codeDialog_form == NULL)
        return -1;

    return 0;
}



static int 
dtb_settings_dialog_button_panel_create(
    DtbSettingsSpeedDialogInfo instance,
    Widget parent
)
{
    
    if (instance->dialog_button_panel == NULL) {
        instance->dialog_button_panel =
            XtVaCreateWidget("dialog_button_panel",
                xmFormWidgetClass,
                parent,
                XmNpaneMaximum, 48,
                XmNpaneMinimum, 48,
                XmNresizePolicy, XmRESIZE_GROW,
                XmNmarginHeight, 7,
                XmNmarginWidth, 7,
                XmNpositionIndex, 1,
                XmNheight, 48,
                NULL);
    }
    if (instance->dialog_button_panel == NULL)
        return -1;

    return 0;
}



static int 
dtb_settings_controlpane_create(
    DtbSettingsSpeedDialogInfo instance,
    Widget parent
)
{
    
    if (instance->controlpane == NULL) {
        instance->controlpane =
            XtVaCreateWidget("controlpane",
                xmFormWidgetClass,
                parent,
                XmNbottomOffset, 0,
                XmNbottomAttachment, XmATTACH_FORM,
                XmNrightOffset, 0,
                XmNrightAttachment, XmATTACH_FORM,
                XmNleftOffset, 0,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 0,
                XmNtopAttachment, XmATTACH_FORM,
                XmNresizePolicy, XmRESIZE_GROW,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNheight, 167,
                XmNwidth, 511,
                XmNy, 18,
                XmNx, 22,
                NULL);
    }
    if (instance->controlpane == NULL)
        return -1;

    return 0;
}



static int 
dtb_settings_speed_create(
    DtbSettingsSpeedDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    if (instance->Speed_rowcolumn == NULL) {
        instance->Speed_rowcolumn =
            XtVaCreateWidget("Speed_rowcolumn",
                xmRowColumnWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 5,
                XmNrightAttachment, XmATTACH_FORM,
                XmNleftOffset, 5,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 15,
                XmNtopAttachment, XmATTACH_FORM,
                XmNadjustLast, True,
                XmNspacing, 0,
                XmNmarginWidth, 0,
                XmNmarginHeight, 0,
                XmNentryAlignment, XmALIGNMENT_BEGINNING,
                XmNorientation, XmVERTICAL,
                XmNy, 16,
                XmNx, 206,
                NULL);
    }
    if (instance->Speed_rowcolumn == NULL)
        return -1;

    label_xmstring = XmStringCreateLocalized("Speed");
    if (instance->Speed_label == NULL) {
        instance->Speed_label =
            XtVaCreateWidget("Speed_label",
                xmLabelWidgetClass,
                instance->Speed_rowcolumn,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->Speed_label == NULL)
        return -1;

    if (instance->Speed == NULL) {
        instance->Speed =
            XtVaCreateWidget("Speed",
                xmScaleWidgetClass,
                instance->Speed_rowcolumn,
                XmNshowValue, True,
                XmNvalue, 25,
                XmNdecimalPoints, 0,
                XmNscaleMultiple, 1,
                XmNmaximum, 60,
                XmNminimum, 12,
                XmNprocessingDirection, XmMAX_ON_RIGHT,
                XmNorientation, XmHORIZONTAL,
                "slidingMode", False,
                XmNheight, 40,
                XmNwidth, 501,
                NULL);
    }
    if (instance->Speed == NULL)
        return -1;

    return 0;
}



static int 
dtb_settings_farnsworth_create(
    DtbSettingsSpeedDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    if (instance->farnsworth_rowcolumn == NULL) {
        instance->farnsworth_rowcolumn =
            XtVaCreateWidget("farnsworth_rowcolumn",
                xmRowColumnWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 5,
                XmNrightAttachment, XmATTACH_FORM,
                XmNleftOffset, 5,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 10,
                XmNtopAttachment, XmATTACH_WIDGET,
                XmNadjustLast, True,
                XmNspacing, 0,
                XmNmarginWidth, 0,
                XmNmarginHeight, 0,
                XmNentryAlignment, XmALIGNMENT_BEGINNING,
                XmNorientation, XmVERTICAL,
                XmNy, 118,
                XmNx, 57,
                NULL);
    }
    if (instance->farnsworth_rowcolumn == NULL)
        return -1;

    label_xmstring = XmStringCreateLocalized("Additional Farnsworth dots");
    if (instance->farnsworth_label == NULL) {
        instance->farnsworth_label =
            XtVaCreateWidget("farnsworth_label",
                xmLabelWidgetClass,
                instance->farnsworth_rowcolumn,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->farnsworth_label == NULL)
        return -1;

    if (instance->farnsworth == NULL) {
        instance->farnsworth =
            XtVaCreateWidget("farnsworth",
                xmScaleWidgetClass,
                instance->farnsworth_rowcolumn,
                XmNshowValue, True,
                XmNvalue, 0,
                XmNdecimalPoints, 0,
                XmNscaleMultiple, 1,
                XmNmaximum, 40,
                XmNminimum, 0,
                XmNprocessingDirection, XmMAX_ON_RIGHT,
                XmNorientation, XmHORIZONTAL,
                "slidingMode", False,
                XmNheight, 40,
                XmNwidth, 501,
                NULL);
    }
    if (instance->farnsworth == NULL)
        return -1;

    return 0;
}



static int 
dtb_settings_separator2_create(
    DtbSettingsSpeedDialogInfo instance,
    Widget parent
)
{
    
    if (instance->separator2 == NULL) {
        instance->separator2 =
            XtVaCreateWidget("separator2",
                xmSeparatorWidgetClass,
                parent,
                XmNbottomOffset, 0,
                XmNbottomAttachment, XmATTACH_FORM,
                XmNrightOffset, 0,
                XmNrightAttachment, XmATTACH_FORM,
                XmNleftOffset, 0,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopAttachment, XmATTACH_NONE,
                XmNseparatorType, XmSHADOW_ETCHED_IN,
                XmNorientation, XmHORIZONTAL,
                XmNheight, 10,
                XmNy, 157,
                XmNx, 70,
                NULL);
    }
    if (instance->separator2 == NULL)
        return -1;

    return 0;
}



static int 
dtb_settings_speed_ok_create(
    DtbSettingsSpeedDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized("OK");
    if (instance->speed_ok == NULL) {
        instance->speed_ok =
            XtVaCreateWidget("speed_ok",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 0,
                XmNrightPosition, 30,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 10,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, True,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNdefaultButtonShadowThickness, 1,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->speed_ok == NULL)
        return -1;

    return 0;
}



static int 
dtb_settings_speed_cancel_create(
    DtbSettingsSpeedDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized("Cancel");
    if (instance->speed_cancel == NULL) {
        instance->speed_cancel =
            XtVaCreateWidget("speed_cancel",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 0,
                XmNrightPosition, 90,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 70,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, True,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNdefaultButtonShadowThickness, 1,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->speed_cancel == NULL)
        return -1;

    return 0;
}



static int 
dtb_settings_dialog_button_panel2_create(
    DtbSettingsCodeDialogInfo instance,
    Widget parent
)
{
    
    if (instance->dialog_button_panel2 == NULL) {
        instance->dialog_button_panel2 =
            XtVaCreateWidget("dialog_button_panel2",
                xmFormWidgetClass,
                parent,
                XmNpaneMaximum, 48,
                XmNpaneMinimum, 48,
                XmNresizePolicy, XmRESIZE_GROW,
                XmNmarginHeight, 7,
                XmNmarginWidth, 7,
                XmNpositionIndex, 1,
                XmNheight, 48,
                NULL);
    }
    if (instance->dialog_button_panel2 == NULL)
        return -1;

    return 0;
}



static int 
dtb_settings_controlpane2_create(
    DtbSettingsCodeDialogInfo instance,
    Widget parent
)
{
    
    if (instance->controlpane2 == NULL) {
        instance->controlpane2 =
            XtVaCreateWidget("controlpane2",
                xmFormWidgetClass,
                parent,
                XmNbottomOffset, 0,
                XmNbottomAttachment, XmATTACH_FORM,
                XmNrightOffset, 0,
                XmNrightAttachment, XmATTACH_FORM,
                XmNleftOffset, 0,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopOffset, 0,
                XmNtopAttachment, XmATTACH_FORM,
                XmNresizePolicy, XmRESIZE_GROW,
                XmNmarginHeight, 0,
                XmNmarginWidth, 0,
                XmNheight, 124,
                XmNwidth, 334,
                XmNy, 29,
                XmNx, 199,
                NULL);
    }
    if (instance->controlpane2 == NULL)
        return -1;

    return 0;
}



static int 
dtb_settings_code_box_create(
    DtbSettingsCodeDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    Arg	args[24];	/* need 19 args (add 5 to be safe) */
    int	n = 0;
    Widget	codeBox_choice_items[2];
    static String	codeBox_choice_names[] =
    {
        "Continental_item", "American_item"
    };
    static String	codeBox_choice_strings[] =
    {
        "Continental", "American"
    };
    int	i = 0;
    Boolean	codeBox_choice_selected[] =
    {
        True, False
    };
    
    if (instance->codeBox_rowcolumn == NULL) {
        instance->codeBox_rowcolumn =
            XtVaCreateWidget("codeBox_rowcolumn",
                xmRowColumnWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightAttachment, XmATTACH_NONE,
                XmNleftOffset, 0,
                XmNleftPosition, 50,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 0,
                XmNtopPosition, 50,
                XmNtopAttachment, XmATTACH_POSITION,
                XmNentryVerticalAlignment, XmALIGNMENT_BASELINE_BOTTOM,
                XmNpacking, XmPACK_TIGHT,
                XmNisHomogeneous, False,
                XmNadjustLast, True,
                XmNspacing, 0,
                XmNmarginWidth, 0,
                XmNmarginHeight, 0,
                XmNentryAlignment, XmALIGNMENT_END,
                XmNorientation, XmHORIZONTAL,
                XmNy, 40,
                XmNx, 51,
                NULL);
    }
    if (instance->codeBox_rowcolumn == NULL)
        return -1;

    label_xmstring = XmStringCreateLocalized(" ");
    if (instance->codeBox_label == NULL) {
        instance->codeBox_label =
            XtVaCreateWidget("codeBox_label",
                xmLabelWidgetClass,
                instance->codeBox_rowcolumn,
                XmNmarginHeight, 8,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->codeBox_label == NULL)
        return -1;

    if (instance->codeBox == NULL) {
        n = 0;
        XtSetArg(args[n], XmNradioBehavior, True);  ++n;
        XtSetArg(args[n], XmNentryClass, xmToggleButtonWidgetClass);  ++n;
        XtSetArg(args[n], XmNnumColumns, 1);  ++n;
        XtSetArg(args[n], XmNisHomogeneous, True);  ++n;
        XtSetArg(args[n], XmNspacing, 0);  ++n;
        XtSetArg(args[n], XmNrowColumnType, XmWORK_AREA);  ++n;
        XtSetArg(args[n], XmNpacking, XmPACK_TIGHT);  ++n;
        XtSetArg(args[n], XmNorientation, XmVERTICAL);  ++n;
        instance->codeBox =
            XmCreateRadioBox(instance->codeBox_rowcolumn,
                "codeBox", args, n);
    }
    if (instance->codeBox == NULL)
        return -1;

    for (i = 0; i < XtNumber(codeBox_choice_strings); i++)
    {
        label_xmstring = XmStringCreateLocalized(codeBox_choice_strings[i]);
        codeBox_choice_items[i] = XtVaCreateWidget(codeBox_choice_names[i],
            xmToggleButtonWidgetClass,
            instance->codeBox,
            XmNset, codeBox_choice_selected[i],
            XmNlabelString, label_xmstring,
            NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    instance->codeBox_items.Continental_item = codeBox_choice_items[0];
    instance->codeBox_items.American_item = codeBox_choice_items[1];
    	dtb_center(instance->codeBox_rowcolumn, DTB_CENTER_POSITION_BOTH);
    return 0;
}



static int 
dtb_settings_separator_create(
    DtbSettingsCodeDialogInfo instance,
    Widget parent
)
{
    
    if (instance->separator == NULL) {
        instance->separator =
            XtVaCreateWidget("separator",
                xmSeparatorWidgetClass,
                parent,
                XmNbottomOffset, 0,
                XmNbottomAttachment, XmATTACH_FORM,
                XmNrightOffset, 0,
                XmNrightAttachment, XmATTACH_FORM,
                XmNleftOffset, 0,
                XmNleftAttachment, XmATTACH_FORM,
                XmNtopAttachment, XmATTACH_NONE,
                XmNseparatorType, XmSHADOW_ETCHED_IN,
                XmNorientation, XmHORIZONTAL,
                XmNheight, 10,
                XmNy, 105,
                XmNx, 30,
                NULL);
    }
    if (instance->separator == NULL)
        return -1;

    return 0;
}



static int 
dtb_settings_code_ok_create(
    DtbSettingsCodeDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized("OK");
    if (instance->code_ok == NULL) {
        instance->code_ok =
            XtVaCreateWidget("code_ok",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 0,
                XmNrightPosition, 40,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 10,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, True,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNdefaultButtonShadowThickness, 1,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->code_ok == NULL)
        return -1;

    return 0;
}



static int 
dtb_settings_code_cancel_create(
    DtbSettingsCodeDialogInfo instance,
    Widget parent
)
{
    XmString	label_xmstring = NULL;
    
    label_xmstring = XmStringCreateLocalized("Cancel");
    if (instance->code_cancel == NULL) {
        instance->code_cancel =
            XtVaCreateWidget("code_cancel",
                xmPushButtonWidgetClass,
                parent,
                XmNbottomAttachment, XmATTACH_NONE,
                XmNrightOffset, 0,
                XmNrightPosition, 90,
                XmNrightAttachment, XmATTACH_POSITION,
                XmNleftOffset, 0,
                XmNleftPosition, 60,
                XmNleftAttachment, XmATTACH_POSITION,
                XmNtopOffset, 5,
                XmNtopAttachment, XmATTACH_FORM,
                XmNrecomputeSize, True,
                XmNalignment, XmALIGNMENT_CENTER,
                XmNdefaultButtonShadowThickness, 1,
                XmNlabelString, label_xmstring,
                NULL);
        XmStringFree(label_xmstring);
        label_xmstring = NULL;
    }
    if (instance->code_cancel == NULL)
        return -1;

    return 0;
}

